### ISSUE TITLE
Optimizations don't recover from passing/returning structs by-value

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#101]
Terra produces hugely inefficient assembly when structs are passed and returned by value. I found this problem while trying to implement operators for 2- to 4-tuples of numeric types in order to provide a convenient vector interface -- as of now, I can't make use of the interface because it doesn't appear to support passing arguments by reference (correction: __add supports macros, so that also offers a way to circumvent the problem).

The gist of the reproduce is here https://gist.github.com/paniq/5c5fe211ef3ec7a52622

**Comment by zdevito** [comment]
Thanks for looking into this in detail. This is definitely an issue -- I
identified part of it as the calling convention code which translates those
calls in an LLVM unfriendly way. This should be fixable. For example, this
is the ASM for the first function when translated correctly:

define { <2 x float>, <2 x float> } @"$add4_val_val"(<2 x float>, <2 x
float>, <2 x float>, <2 x float>) #0 {
entry:
  %4 = fadd <2 x float> %0, %2
  %5 = fadd <2 x float> %1, %3
  %6 = insertvalue { <2 x float>, <2 x float> } undef, <2 x float> %4, 0
  %7 = insertvalue { <2 x float>, <2 x float> } %6, <2 x float> %5, 1
  ret { <2 x float>, <2 x float> } %7
}

assembly for function at address 0x9732070
0x9732070(+0): vaddps xmm0, xmm0, xmm2
0x9732074(+4): vaddps xmm1, xmm1, xmm3
0x9732078(+8): ret

I will try to get to this some time next week if possible.
