### ISSUE TITLE
Compiler crash on deferred non-inlined function call with struct as argument

### ISSUE THREAD

**Issue by 0----0** [zdevito/terra#102]
I was trying to use deferred calls for some strange purpose when I ran into this weird crash.  I've done my best to get it into its minimal form here:
```lua
local struct Type {
        field: int
}

local terra foo(obj: Type) end
foo:setinlined(false)

local terra bar()
        var obj: Type
        defer foo(obj)
        return
end

bar()
```
With terra-Linux-x86_64-04fb3e2, this gives me the following error message:
```
While deleting: i32 %.fca.0.insert.fca.0.extract
Use still stuck around after Def is destroyed:  %.fca.0.insert.fca.0.extract = extractvalue <null operand!>, 0
terra: Value.cpp:80: virtual llvm::Value::~Value(): Assertion `use_empty() && "Uses remain when a value is destroyed!"' failed.
```
With the latest git build, it just segfaults.

It's hard to outline the exact conditions of the error.  Letting `foo` inline, passing `obj` by reference, or passing an `int` instead seems to avoid the issue.

I hope this is helpful.

OS: Arch Linux x86_64

**Comment by zdevito** [comment]
Thanks for the bug report. It seems to have something to do with the
interaction between the return at the end of the function and the defer
statement.  I will probably get to this sometime next week.
