### ISSUE TITLE
Syntax highlighter

### ISSUE THREAD

**Issue by LennyPenny** [zdevito/terra#108]
Are there any syntax highlighters for any text editors?

**Comment by zdevito** [comment]
I don't have any official ones, but normally what I do is take the Lua syntax highlighter for an editor and add the following terra-specific keywords:

    "terra", "var","struct","union","quote","import","defer","escape"

The other syntactical features of the language are identical to Lua so it normally works pretty well.

**Comment by LennyPenny** [comment]
Oh I didn't thank of that, thanks!
