### ISSUE TITLE
Expose Terra's "convenient" readline for custom REPL's?

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#109]
While I was writing a REPL for my toy language I noticed that Terra's (Lua's) internal ``read`` doesn't support browsing the input history, or even handling the up-down keys, but Terra's REPL does; I rummaged a bit in the code and it appears this is due to ncurses / readline support?

Would it be possible to expose either history handling or up-down-keys to Terra code so users can build convenient REPL's too?

**Comment by zdevito** [comment]
I use the linenoise library (https://github.com/antirez/linenoise) in the interpreter executable. You can get to the function from Terra, though it is a bit convoluted because the linenoise functions are included as C++:

    local ffi = require("ffi")
    linenoise = terralib.externfunction("__Z9linenoisePKc", rawstring -> rawstring)
    local result = ffi.string(linenoise("mypromt:"))
    print("use wrote",result)
