### ISSUE TITLE
terralib.includec doesn't work on  Windows 10

### ISSUE THREAD

**Issue by gtotoy** [zdevito/terra#110]
std = terralib.includec("stdio.h")

terra main()
    std.printf("he");
end

main()

![image](https://cloud.githubusercontent.com/assets/2191588/9157298/21378264-3ebe-11e5-8edd-3630a9bcc1be.png)

**Comment by zdevito** [comment]
Are you using the binary version of Terra? Currently it is Windows 8 specific, I believe.

**Comment by gtotoy** [comment]
Yes, I use the binary version and I tested on Windows 7 and it works there.

**Comment by zdevito** [comment]
The binaries will probably need to be rebuilt on a windows 10 machine. I don't have one at the moment, but I will make a new release when I upgrade.

**Comment by gtotoy** [comment]
Thanks

**Comment by minglu199192** [comment]
Hi~ I use the binary version and test it on Windows 10, 7, 8.1. All three systems had the same problems. I installed visual studio 2013, CUDA 7.0, Windows SDK. Did I need to setup some environmental variables manually to run the code ?

**Comment by HollisJoe** [comment]
I use the binary version and test it on Windows 10, 7, 8.1. All three systems had the same problems of you. Did your solution solve the problem?

**Comment by minglu199192** [comment]
@HollisJoe , the installation directory should be the default directory, like C:\path\to\your\visual studio.

**Comment by minglu199192** [comment]
@HollisJoe If you use opt, the problem can also be solved by changing to default path.

**Comment by HollisJoe** [comment]
My vs2013 is installed on drive D, must be installed on the drive C?

**Comment by HollisJoe** [comment]
@minglu199192 Sorry! I didn't catch your words! Could you please give more details?

**Comment by minglu199192** [comment]
@HollisJoe  must be installed using visual studio's default path

**Comment by mxgbs** [comment]
Hi Ming @minglu199192,

Could you please release more details? Do you mean we need to install terra in the visual studio path or we need to re-install visual studio using the default path? I'm also working on opt. What you mean by changing to default path? Thank you.

**Comment by minglu199192** [comment]
Re-install visual studio using the default path should solve the problem.  Besides, it will be easier to compile it in Linux.

**Comment by mxgbs** [comment]
OK. Thank you. We use a server desktop thus I could not do that. Have no
idea what should I include in the environment variable to make that work.

Sincerely,

Yan

**Comment by elliottslaughter** [comment]
Newer Windows binaries are now available here: #323. If anyone still has problems with them, please open a new issue to discuss this.
