### ISSUE TITLE
Specific code can cause Terra to hang & freeze the machine

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#113]
On my Ubuntu, with the most recent Terra from master (a7089683af3a45d04768f57a4e9674f8185590bf), a specific handcrafted piece of code causes Terra to lock up during compilation and allocate all main memory until the system eventually freezes.

```
local terra boom (m : float) : float
    return m % 3.14159
end

print(boom(0))
```

I assume the problem has to do with modulating floating point numbers. After checking the terralib source code I suspect that the problem might also very well be with LLVM (I use 3.5.0), but I have no easy means to verify this.

A quick Google brought up this. frem is involved and the crash behavior sounds the same. http://lists.llvm.org/pipermail/llvm-dev/2015-February/082071.html

Googling a bit for the revisions mentioned in the response, it seems we have a winner. http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20141208/248529.html

Of course I'll have to verify by updating tomorrow. I suggest advising not to use LLVM 3.5.0 in the manual.

**Comment by paniq** [comment]
Updating to LLVM 3.6.2 does indeed fix the problem.

**Comment by rdebath** [comment]
I go this too with llvm 3.5.0 on Debian jessie, the virtual memory allocated by terra exceeded the memory in the test machine (4G) in about 4 seconds. This would have locked up any desktop environment on that machine.

**Comment by zdevito** [comment]
I am going to close this since it is a LLVM bug that has been fixed. Thanks for looking into it and finding out where the problem was.
