### ISSUE TITLE
terra.disas() no longer seems to print assembly output

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#116]
Calling ``disas()`` on functions only outputs LLVM IL and no longer prints the generated assembly, a feature that I often relied on during debugging. The name of the function is now misleading.

**Comment by zdevito** [comment]
I didn't remove the asm output, so this is probably a bug with getting the right meta-data somewhere. What version of LLVM and what OS was this on?

**Comment by paniq** [comment]
latest terra trunk, Ubuntu 15.04, LLVM 3.6.2 (I'm using their prebuilt binaries)

**Comment by zdevito** [comment]
Thanks, I can reproduce this -- it requires MCJIT on Linux, which is required on 3.6 but on optional on 3.5. I will try to track down what is going on.

**Comment by paniq** [comment]
Fantastic, thanks!
