### ISSUE TITLE
Partial failure with Debian multiarch

### ISSUE THREAD

**Issue by rdebath** [zdevito/terra#117]
I've compiled and successfully run on a x86_64 install of Debian stable/jessie.
I needed to install the `build-essential clang libclang-dev llvm-dev zlib1g-dev ncurses-dev` Debian packages.

But had some issues
- Minor issue; it would have been nice if it had complained _explicitly_ about building on an x86 32 bit install before it did anything that wouldn't be fixed by a `make clean`. The 64bit build was still broken after I had done the `make` and `make clean`.
- Minor issue; it did not use the 64bit compiler in the 32bit multi-arch environment despite the full 64bit development system being available... this is not really a surprise of course.
- When I tried to run the tests for the successfully built 64bit executable it had a small failure in the 64bit environment and a weird failure under the (mostly) 32bit environment.

These were the test failures on the full 64bit environment. 

```
488 tests passed. 2 tests failed.
...
$ ./terra tests/sgemm.t
LLVM ERROR: Do not know how to split the result of this operator!

$ ./terra tests/avxhadd.t
LLVM ERROR: Do not know how to split the result of this operator!

$ llvm-config --version
3.5.0
```

This was the result of running the same executable in a 32bit multiarch environment; note that it is working with _some_ `terra` code, not just `luajit` code. To me this looks like you're calling the `ld` command but allowing it to default to a 32bit link when you want a 64bit one.

```
$ file -L ./terra
./terra: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=7820baa94d5b278a2b1e89cebd55251d6746ff6d, not stripped
$ file -L /bin/sh
/bin/sh: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ee05cfc6895aeced18a7a8dc445cba410984151a, stripped
$ ./terra tests/bf.t
Hello World!
$ ./terra tests/hello.t
/usr/bin/ld: i386:x86-64 architecture of input file `/tmp/terra-5815fc.o' is incompatible with i386 output
collect2: error: ld returned 1 exit status
llvm:

stack traceback:
        [C]: in function 'saveobj'
        src/terralib.lua:4299: in function 'saveobj'
        tests/hello.t:7: in main chunk
$ sc ./terra tests/hello.t
hello, world
$ size ./terra
   text    data     bss     dec     hex filename
43664773        2453912   82984 46201669        2c0fb45 ./terra
$ ldd ./terra
        linux-vdso.so.1 (0x00007ffd4b913000)
        libncurses.so.5 => /lib64/libncurses.so.5 (0x00007fc707820000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fc7075f6000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc7073da000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc7071d6000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc706ecb000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc706bc9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc7069b3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc706796000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc7063ec000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc707a6d000)
$
$ file /tmp/hello.*
/tmp/hello.arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=c00ae638edc8db236999b4d2a9372034cea3fbbf, stripped
/tmp/hello.i86: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=1a4d6e6e43fef8e730efd224568d4a6d37d9ec5b, stripped
/tmp/hello.ppc: ELF 32-bit MSB executable, PowerPC or cisco 4500, version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.32, BuildID[sha1]=ef050dbf7bcbdd6690383d6ac675a729f16e1c98, stripped
/tmp/hello.x64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=923b3b099c29b13feac6e9536f5994ee1dfa7392, stripped
$ /tmp/hello.i86
Hello, world!
$ /tmp/hello.x64
Hello, world!
$ /tmp/hello.arm
Hello, world!
$ /tmp/hello.ppc
Hello, world!
$

```

PS: Fixed the package list.

**Comment by zdevito** [comment]
The failures for the 64-bit environment are because your machine doesnt have the avx instructions those tests are using (its hard to check this in the tests, so I didn't bother).

This runs into problems because we don't have full support for 32-bits yet. I made issue #119 to track the bugs related to 32-bit support.

**Comment by rdebath** [comment]
Please re-read this. I am not talking about a 32bit build.
This is a 64bit build in a mostly 32bit system. 

Debian multiarch allows 64bit executables to be compiled and run within this environment.

The initial build did not notice that the operating system was 64bit capable and attempted to compile a 32bit executable; this is not unexpected, but could be changed.

When the executable was compiled and successfully tested in a full 64bit environment I switched to the '32bit' environment and attempted to run the program. 

This works perfectly for all LuaJIT code.

It works for SOME terra code; the failure is nothing to do with C calling conventions. 
I think this error means that terra is successfully creating a 64bit object file in /tmp but is then telling `ld` (collect) to convert it to a 32bit executable or shared library. This is a simple flag that is controlled by the linker script or the`--oformat` command line option.
```
/usr/bin/ld: i386:x86-64 architecture of input file `/tmp/terra-5815fc.o' 
is incompatible with i386 output
```

I've done a similar thing myself ([with a far more trivial compiler](https://github.com/rdebath/Brainfuck/blob/master/tritium/bfi.ccode.c)) where I call the `clang` command and so need to use the `-m64` option to enforce the 64bit compile in a mixed environment.

eg: `clang -m64 -fwrapv -fpic -shared`

**Comment by rdebath** [comment]
To check for the AVR instructions clang and GCC have the cpuid.h file, this make it easy to check those flags. I do it like below for SSE4.2, so I can have a command line flag to turn it off too.  It would be very similar for the AVR sets. 

```
#ifndef __SSE4_2__
#if defined(__GNUC__) && ((__GNUC__>4) || (__GNUC__==4 && __GNUC_MINOR__>=4))
#include <cpuid.h>
#endif
#endif

static void
check_for_sse4_2(void)
{
#ifdef __SSE4_2__
    use_sse4_2 = 1;
#else
    use_sse4_2 = 0;

#ifdef bit_SSE4_2
    int i;
    unsigned a, b, c, d;

    i =  __get_cpuid(1, &a, &b, &c, &d);

    if (i && (c & bit_SSE4_2))
        use_sse4_2 = 1;
#endif
#endif
}
```

**Comment by zdevito** [comment]
I wasn't aware of the existence of multiarch so this is the first time I am seeing these issues. I don't have a 32-bit install to easily test this with, but if you figure out what the changes should be to the makefile to get this to work, I can merge them in.

**Comment by elliottslaughter** [comment]
@rdebath If you still care about this, can you confirm that the issue still happens on master? Ideally check two configurations:

 1. the traditional Makefile
 2. CMake

**Comment by elliottslaughter** [comment]
I'm going to close this for now, if someone wants this we really need volunteers to step forward to make it happen. If someone finds this issue and is willing to do that, ping it and we can talk about what it will take.
