### ISSUE TITLE
Missing Lua C API Exports in Terra Binary

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#124]
I tried to set up a Lua interpreter context in Terra today and noticed using ``nm`` that only used symbols of the LuaJIT interface are exported by terra; many functions such as ``lua_open``, ``lua_pop``, ``lua_tostring`` apparently have been culled by the linker from the import table and can not be used. 

Would it be possible to link Terra with the full LuaJIT library instead? I don't know how it's done on Win32 but on Posix, the respective linker flag is ``-Wl,--whole-archive``

**Comment by zdevito** [comment]
I believe terra is linked against luajit with --whole-archive. The problem
is that those functions are all defined as macros in luajit:

DNab404696:src zdevito$ cat *.h | grep lua_open
#define lua_open() luaL_newstate()
DNab404696:src zdevito$ cat *.h | grep lua_pop
#define lua_pop(L,n) lua_settop(L, -(n)-1)
DNab404696:src zdevito$ cat *.h | grep lua_tostring
#define lua_tostring(L,i) lua_tolstring(L, (i), NULL)

**Comment by paniq** [comment]
aha! of course. well that clears things up. thanks and sorry for the bother.
