### ISSUE TITLE
Latest Terra Windows build freezes when code contains modulo operation

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#133]
This is a resurgence of https://github.com/zdevito/terra/issues/113 in the latest Windows binary of Terra, which is built with LLVM 3.5.0 and therefore contains the same problem.

I would appreciate getting a more recent binary, or an updated makefile and build instructions that work with with LLVM 3.6.2, in order to be able to test for https://github.com/zdevito/terra/issues/132 and other issues.

I tried to assemble such a build myself but I have no idea how to fix some of the issues that came up.

**Comment by zdevito** [comment]
My plan is to not update the binary releases to 36 until I can get CUDA working with LLVM 3.6, which I haven't had time to debug. LLVM 3.6 should work on Windows by just updating the path in `msvc/Makefile`, but I haven't had time to try it yet. You can also work around the modulo problem by using the `fmodf` instead:

    local fmodf = terralib.externfunction("fmodf",{float,float} -> float)

**Comment by elliottslaughter** [comment]
There have multiple fixes for Windows going in recently, including updating LLVM support to 6 and newer MSVC versions. If anyone here is still interested, please try master and file a new issue if there continue to be problems.
