### ISSUE TITLE
Compiling on  FreeBSD

### ISSUE THREAD

**Issue by JohnMH** [zdevito/terra#135]
The Makefile should be altered, to detect FreeBSD and to prefer llvm36 (as it can't be compiled with 37, some includes moved to different locations). On my system, llvm-config doesn't exist, but llvm-config36 and llvm-config37 does.

EDIT: I see that the README says "Terra uses LLVM 3.5, Clang 3.5", but Terra successfully compiles with 3.6, on FreeBSD.

**Comment by zdevito** [comment]
Does the build work if you create a `Makefile.inc` and point LLVM_CONFIG to
your llvm-config36 using the instructions at
http://terralang.org/getting-started.html#building-terra?

**Comment by JohnMHarrisJr** [comment]
I can find out, later today. I altered the Makefile to call `llvm-config36` instead of `llvm-config`, and it worked for me.

On November 23, 2015 10:01:52 AM EST, Zachary DeVito <notifications@github.com> wrote:
>Does the build work if you create a `Makefile.inc` and point
>LLVM_CONFIG to
>your llvm-config36 using the instructions at
>http://terralang.org/getting-started.html#building-terra?
>
>
>On Mon, Nov 23, 2015 at 9:28 AM, John M. Harris, Jr. <
>notifications@github.com> wrote:
>
>> The Makefile should be altered, to detect FreeBSD and to prefer
>llvm36 (as
>> it can't be compiled with 37, some includes moved to different
>locations).
>> On my system, llvm-config doesn't exist, but llvm-config36 and
>> llvm-config37 does.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/zdevito/terra/issues/135>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zdevito/terra/issues/135#issuecomment-158961181

-- 
Sent from my Android device. Please excuse my brevity.

**Comment by JohnMHarrisJr** [comment]
Actually, from what I did, I'd say that almost definitely would work. I can't see any reason that it wouldn't, since I did essentially that, just in the Makefile itself, instead of the included.

On November 23, 2015 10:01:52 AM EST, Zachary DeVito <notifications@github.com> wrote:
>Does the build work if you create a `Makefile.inc` and point
>LLVM_CONFIG to
>your llvm-config36 using the instructions at
>http://terralang.org/getting-started.html#building-terra?
>
>
>On Mon, Nov 23, 2015 at 9:28 AM, John M. Harris, Jr. <
>notifications@github.com> wrote:
>
>> The Makefile should be altered, to detect FreeBSD and to prefer
>llvm36 (as
>> it can't be compiled with 37, some includes moved to different
>locations).
>> On my system, llvm-config doesn't exist, but llvm-config36 and
>> llvm-config37 does.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/zdevito/terra/issues/135>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zdevito/terra/issues/135#issuecomment-158961181

-- 
Sent from my Android device. Please excuse my brevity.

**Comment by elliottslaughter** [comment]
Some fixes went into the Makefile for FreeBSD a while back, if anyone is still interested please try master and open a new issue if there are further problems.
