### ISSUE TITLE
Can't find "integrated" headers (Mint 17.2)

### ISSUE THREAD

**Issue by Goobley** [zdevito/terra#137]
I'm using Mint 17.2, I've tried both the binaries and building from source. The errors are the same. Everything builds fine (using a binary of clang 3.5.2 in my home directory, tried both on and not on PATH). Terra functions JIT fine and the REPL appears to work, however attempting to include any standard header eg `math.h` or `stdio.h` causes `fatal error: file could not be found`.

I have checked that `stddef.h` (the culprit in the case of `stdio.h`) has an entry in `internalizedfiles.h`. If I manually add the clang include path to `clangpaths.h` and recompile (I know genclangpaths.lua avoids this). Then it gets a bit further before being unable to find `<sys/cdefs.h>`. The default compiler on this platform is gcc-4.8 and I also have clang-3.7 on the PATH.

Any ideas would be much appreciated. I had terra working about 6 months ago on a different system with no trouble, but it just doesn't seem to want to work here.

**Comment by zdevito** [comment]
I have seen reports of this before, but I have never been able to reproduce the problem on my linux machines which run ubuntu, making it difficult to track down. My guess is that there is some behavior in clang that makes the header file search proceed differently and skip the internalized files as a search option. I will try to get a VM running to reproduce this when I get some free time.

**Comment by Goobley** [comment]
Last I checked it was running fine on my mac, I'll try and compare search locations etc. and report back.

**Comment by zdevito** [comment]
Thanks for tracking this down and submitting a patch!
