### ISSUE TITLE
New build system causes problems on Mint

### ISSUE THREAD

**Issue by Goobley** [zdevito/terra#142]
Commit c31d134 breaks the default build process on on Mint (debian based for me), it makes `terra` use the default system compiler, which may be a good thing as the compiler may be more up to date. However the default compiler for this distro (based on Ubuntu 14.04) is gcc-4.8. When terra is built under gcc 4.8 the `testdebug.t` fails with a segmentation fault. If I override CXX and CC to be a version of clang (either 3.5.2 used for terra libraries, or 3.7.0 on the PATH) everything works fine. 

In the previous build system the makefile was happy to find the binary of clang used for the terra libraries. I don't know what the best approach is here, possibly adding the TERRA_CC/TERRA_CXX variables back into the makefile to make them easy to override, as a compromise between the two methods?

**Comment by zdevito** [comment]
I changed it back to default to clang when CXX and CC are not set in e3ccbd3. Hopefully this work better.

**Comment by Goobley** [comment]
As far as I'm aware, CXX and CC can't be set like that because they have a default value see [here](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) when they are not set in the shell. My testing seems to agree with this, as even after that commit it defaults to gcc/g++. Hence my recommendation of using TERRA_CXX still stands.
