### ISSUE TITLE
Compile failure when llvm is built without static libraries

### ISSUE THREAD

**Issue by expipiplus1** [zdevito/terra#150]
If only the shared libraries for LLVM are visible then the compile fails due to `build/dep_objects/llvm_list` containing a list of shared libraries rather than the static libraries that unpacklibraries.lua expects.

It would be nice if the compile failed a little more gracefully should the static libraries not be found.

The OS I'm using is Ubuntu 14.04

**Comment by elliottslaughter** [comment]
As noted in #308 this is partially fixed by the CMake build, except at the moment Clang is still required to be statically linked.

Closing this issue in favor of the newer one just to avoid duplication on the issue tracker.

**Comment by elliottslaughter** [comment]
Er, meant to reference #309.

**Comment by expipiplus1** [comment]
Thanks!
