### ISSUE TITLE
intermittent JIT failure

### ISSUE THREAD

**Issue by brandonbloom** [zdevito/terra#156]
About 70% of the time when I run [this code](https://github.com/brandonbloom/terra-java/tree/17f4f888d33e53e56e019c001aa405214985963f) (via `terra example.t`), I get the following stack trace:

```
attempt to index a function value
stack traceback:
	[C]: in function 'addvalue'
	src/terralib.lua:580: in function 'jitvalue'
	src/terralib.lua:595: in function 'jit'
	src/terralib.lua:607: in function 'getpointer'
	src/terralib.lua:673: in function 'minute'
	example.t:21: in main chunk
```

The remaining 30% of the time, the code runs through just fine. It seems like some kind of race condition or memory ownership bug in the JIT.

Issue exists in both on OSX in both the 2015-08-03 and 2016-02-26 releases.

If this isn't enough information, please let me know and I'll do my best to produce a minimal reproduction or help you get the problematic code running.

**Comment by zdevito** [comment]
Terra makes a distinction between functions (which may have 0 or more definitions) and function definitions, which are one concrete implementation. This code needs to explicitly extract the definition first to add it to another function:
 
```
diff --git a/terra-java/declare.t b/terra-java/declare.t
index cf39bf4..e9d4e73 100644
--- a/terra-java/declare.t
+++ b/terra-java/declare.t
@@ -131,7 +131,7 @@ function P.method(T, ret, name, params)
   end
 
   if T.methods[name] then
-    T.methods[name]:adddefinition(fn)
+    T.methods[name]:adddefinition(fn:getdefinitions()[1])
   else
     T.methods[name] = fn
   end
@@ -170,9 +170,10 @@ P.field = function(T, static, typ, name)
     return self._obj:[get](fid)
   end
 
-  T.methods[name]:adddefinition(terra(self : T, value : typ)
+  local tmp = terra(self : T, value : typ)
     self._obj:[set](fid, value)
-  end)
+  end
+  T.methods[name]:adddefinition(tmp:getdefinitions()[1])
 
 end
```

I updated the API to produce a better error message for this case. I also want to rethink how function definition and declaration work in Terra and hopefully simplify this API in the future.

**Comment by brandonbloom** [comment]
Wow, awesome, this works perfectly now. Thank you! I guess this was the first time I exercised that overloading code path.

I'm curious: What was causing this failure to be inconsistent?

**Comment by zdevito** [comment]
I am not sure -- it wasn't inconsistent for me -- but a common source of
non-determinism is using Lua's `pairs(table)` which results in a
non-deterministic iteration order for table keys.

**Comment by brandonbloom** [comment]
Ah, I guess that makes sense: Different iteration orders either found the correct overload or the function pretending to be an overload.
