### ISSUE TITLE
Can't use dot indexing on table entries with names 'quote' or 'union'

### ISSUE THREAD

**Issue by sarostru** [zdevito/terra#163]
I was trying to use a lua library that provides a couple of classes that have methods named `quote` and `union`, in particular `json.quote` and `set.union` from this library, https://github.com/dromozoa/dromozoa-commons.  Trying to access those methods will trigger a failure like the one shown here from a terra repl session:
```
> json = require "dromozoa.commons.json"
table: 0x41f38640
> inspect = require "inspect"
> print(inspect(json.quote))
[string "stdin"]:1: '<name>' expected near 'quote'
```
 This may be by design, since those are both keywords in terra and I don't know how they are implemented so if this makes sense to you feel free to close the issue.

It is straightforward to work around as renaming the `quote` and `union` methods in the library to `_quote` and `_union` and things works fine.

Here is a more general example of the behavior in a simple table:
```
> T = {quote = 5}
[string "stdin"]:1: unexpected symbol near '='
> T = {union = 6}
[string "stdin"]:1: unexpected symbol near 'union'
> T = {}
> T["union"] = 6
> T["quote"] = 5
> T.union
[string "stdin"]:1: '<name>' expected near 'union'
> T.quote
[string "stdin"]:1: '<name>' expected near 'quote'
> print(T["union"])
6
> print(T["quote"])
5

```
Thanks,
Scott

**Comment by zdevito** [comment]
The errors are correct behavior because they are keywords in Terra,
unfortunately. This is why long-established languages are very sensitive to
adding new keywords.

Your work around here should work fine.

**Comment by sarostru** [comment]
Thanks Zach, that was what I suspected once I figured out what was going wrong.

Just wanted to also say that I love what you are doing with this language, it has me excited about writing numeric code in a way I haven't felt in a long time.  Writing lua code sure beats writing C++ templates :+1: .

Closing the issue since it is correct behaviour.
