### ISSUE TITLE
Error calling intrinsic "llvm.powi.f32" on Windows

### ISSUE THREAD

**Issue by jimbo00000** [zdevito/terra#164]
The following test case exits with error on Windows 7,8, and 10 with Terra built against LLVM 3.5.2 and against 3.6.2, as well as terra-Windows-x86_64-332a506.

```
local powi = terralib.intrinsic("llvm.powi.f32",{float,int32} -> float)

terra foo(v : float, w : int32)
    return powi(v,w)
end

local test = require("test")

test.eq(foo(8,2),64)

```
## Output

Windows 7:

```
LLVM ERROR: Program used external function '__powisf2' which could not be resolved!
0   C                                   0x00007ff8adf1fe34 LdrGetDllPath + 1412
```

Windows 8, 10:

```
0   unknown                             0x0000000000000000
1   C                                   0x00007ffdfeb87e27 lua_yield + 61319
2   unknown                             0x0000000027f403b8
```

**Comment by paniq** [comment]
Can confirm, have the same issue with my build.

**Comment by zdevito** [comment]
I think this is because the Windows builds use the MSVC which does not
include compiler-rt, the library that these intrinsics get lowered to. See
https://internals.rust-lang.org/t/compiler-rt-builtins-on-msvc/2684

A possible workaround would be to have clang generate the right function
for use in windows:

C = terralib.includecstring[[
  #include<math.h>
  double powi(double a, int b) {
    return pow(a,b);
  }
]]


But I am not in front of a windows machine to test it.

**Comment by paniq** [comment]
That still leaves problems with other intrinsics. What would be the "proper" way to address this?

**Comment by zdevito** [comment]
I'm not sure what the right way is to address this issue. For now I am going to wait and see how the Rust developers end up handling it and other windows library issues. It's possible that the way LLVM works on windows will change over time and make the resolution easier.

**Comment by randrew** [comment]
I got stuck on this when playing with terra -- I need to use SSE2 (and SSE4) operations (more than the ones used automatically by the vector types), but I couldn't find a way to do it on Windows, so I had to give up.

If there's anything I could do to help make SSE instructions work, point me in the right direction, and I'll see if I can help.

**Comment by elliottslaughter** [comment]
@jimbo00000 If you still care about this, can you confirm that it reproduces on master, ideally testing with LLVM 6?

**Comment by jimbo00000** [comment]
Hi, I haven't used this for a long time - OK with me to let it slide.
