### ISSUE TITLE
example of how to cast lua print to varargs terra function does not work

### ISSUE THREAD

**Issue by adrian-gierakowski** [zdevito/terra#166]
```lua
tprint = terralib.cast( terralib.types.funcpointer({},{},true), print )
```

the above ( quote from here: https://github.com/zdevito/terra/releases/tag/release-2016-03-25 ) generates following error:

> src/terralib.lua:1365: declaration specifier expected near ','
stack traceback:
	[C]: in function 'cdef'
	src/terralib.lua:1365: in function 'cstring'
	src/terralib.lua:4080: in function 'cast'
	tests/benchmark_fannkuchredux.t:25: in main chunk

I inserted a `print( cdef )` just before src/terralib.lua:1365, and the result was: 
```
typedef void (*function)(,...)
```
which explains the error

then I tried the following:
```lua
tprint = terralib.cast( terralib.types.funcpointer({int},{},true), print )
```
and `funcpointer` call succeeded with cdef string looking like this: 
```
typedef void (*function_5)(const char *,...)
```

however another error was thrown by cast:

> cannot convert 'function' to 'void (*)()'
> stack traceback:
> 	[C]: in function 'cast'
> 	tprint_test.t:1: in main chunk

**Comment by zdevito** [comment]
In retrospect, it turns out that this approach doesn't actually work at all. Instead I updated the release notes with an example of how to get vararg-like behavior using a macro (https://github.com/zdevito/terra/blob/master/tests/varargluacall.t). This is exactly what Terra used to do internally in this situation.

**Comment by adrian-gierakowski** [comment]
@zdevito : cool, thanks! I actually implemented a similar one, just without the clever typecache trick :)
It might be also useful to have an optional return type argument in case the function is supposed to return something.

One more comment about wrapping lua print and using it from terra: character strings will not be printed correctly, for example calling : 
```
tprint( "message" )
``` 
prints: `cdata<const char *>: 0x...`

So I created a wrapper around lua print, which automatically casts `char*` and `const char*` to lua string:
````lua
local ffi = require 'ffi'
local const_char_str_t = ffi.typeof( ffi.new( "const char*" ) )
local char_str_t = ffi.typeof( ffi.new( "char*" ) )

local is_char_str = function ( v )
  return type( v ) == 'cdata' and ( ffi.typeof( v ) == char_str_t or
                                    ffi.typeof( v ) == const_char_str_t )
end


local print_autocast = function ( ... )
  local args = terralib.newlist { ... }
  args = args:map( function ( v )
    if is_char_str( v ) then v = ffi.string( v ) end
    return v
  end )
  print( unpack( args ) )
end
```
