### ISSUE TITLE
Suggestion: change repo description for better GitHub discovery

### ISSUE THREAD

**Issue by 0joshuaolson1** [zdevito/terra#167]
I don't remember how I found Terra, but searching for '(system[s]) programming language' is normally how I discover these things. There may be others like me who aren't specifically into Lua but would find the seamless C interop and metaprogramming here tantalizing.

**Comment by 0joshuaolson1** [comment]
From the website:

> Terra is a low-level system programming language that is embedded in and meta-programmed by the Lua programming language

**Comment by zdevito** [comment]
I updated it.
