### ISSUE TITLE
p:next(p.name) accepts keywords

### ISSUE THREAD

**Issue by elliottslaughter** [zdevito/terra#171]
Terra's custom language parser does not reject keywords for `p:next(p.name)`. This makes it possible to write non-sensical code such as:

```
> do import "regent" task g() var var = 0 end end
> g:compile()
```

(in Regent), whereas Terra proper is able to reject this as a parse error.

```
> terra f() var var = 0 end
[string "stdin"]:1: '<name>' expected near 'var'
```

If `p:next(p.name)` rejected keywords, Regent would be able to give a nice error just like Terra does above.

**Comment by zdevito** [comment]
You want to use p:expect(p.name) in that case. Next doesn't take any
arguments.

**Comment by elliottslaughter** [comment]
Yup, that fixes it. I guess what I didn't know (aside from next not taking a parameter) was that expect actually returned the token parsed.
