### ISSUE TITLE
Void pointers in C structs

### ISSUE THREAD

**Issue by alexbw** [zdevito/terra#172]
**EDIT**: Torch was defining each of these types explicitly with FFI upon load. Not a Terra problem. Have some segfaults now, but those are also probably my fault.

Trying to interact with the Torch numeric library using Terra. Torch is a little strange, but hopefully it's possible to have it play nicely with Terra.

Torch abuses C macros to define its data types (it's all C, no C++, so it fakes templates, in a way). That actually seems to be fine with Terra, I'm able to successfully import all the function and struct definitions from the main Torch library (`TH/TH.h` if you're interested in poking around). I can see all the methods and types that I would expect to see using `terralib.includec`.

The core Torch data type, the `Tensor`, is a nested struct with the following layout:

```
typedef struct THAllocator {
  void* (*malloc)(void*, long);
  void* (*realloc)(void*, void*, long);
  void (*free)(void*, void*);
} THAllocator;

typedef struct THDoubleStorage
{
    double *data;
    long size;
    int refcount;
    char flag;
    THAllocator *allocator;
    void *allocatorContext;
} THDoubleStorage;

typedef struct THDoubleTensor
{
   long *size;
   long *stride;
   int nDimension;
   THDoubleStorage *storage;
   long storageOffset;
   int refcount;
   char flag;
} THDoubleTensor;
```

`Tensors` are optionally strided and offsetted views on contiguous memory in a `Storage` object, and `Storage` objects carry around their data, some metadata, and an `Allocator` object that points to internal memory management methods.

The following snippet of code:
```
local torch = require 'torch'
terralib.includepath = 'path/to/my/torch/headers'
local TH = terralib.includec('TH/TH.h')

local emptyTensor = torch.zeros(10)
local terraEmptyTensor = terralib.cast(TH.THDoubleTensor,emptyTensor) -- fails here
```

fails with this traceback:
```
src/terralib.lua:1337: attempt to redefine 'THAllocator'
stack traceback:
	[C]: in function 'cdef'
	src/terralib.lua:1337: in function 'definecstruct'
	src/terralib.lua:1394: in function 'cstring'
	src/terralib.lua:1380: in function 'cstring'
	src/terralib.lua:1329: in function 'definecstruct'
	src/terralib.lua:1394: in function 'cstring'
	src/terralib.lua:1380: in function 'cstring'
	src/terralib.lua:1329: in function 'definecstruct'
	src/terralib.lua:1394: in function 'cstring'
	src/terralib.lua:4117: in function 'cast'
	ffi-tensor-defs.t:9: in main chunk
```

Also trying to use the Tensor type as either input or output type of terra functions fails with the same error, but the above snippet is the most minimal example.

The documentation says Terra has no void type. Is that a cause of this issue?
Also, should I expect Terra to deal well with nested structs like this?

**Comment by alexbw** [comment]
Even more self-contained:

```
local torch = require 'torch'
local TH = terralib.includecstring [[
typedef struct THAllocator {
  void* (*malloc)(void*, long);
  void* (*realloc)(void*, void*, long);
  void (*free)(void*, void*);
} THAllocator;

typedef struct THDoubleStorage
{
    double *data;
    long size;
    int refcount;
    char flag;
    THAllocator *allocator;
    void *allocatorContext;
} THDoubleStorage;

typedef struct THDoubleTensor
{
   long *size;
   long *stride;
   int nDimension;
   THDoubleStorage *storage;
   long storageOffset;
   int refcount;
   char flag;
} THDoubleTensor;
]]


local emptyTensor = torch.zeros(10)
local terraEmptyTensor = terralib.cast(TH.THDoubleTensor,emptyTensor)
```

**Comment by zdevito** [comment]
I'll take a look at this tomorrow. It seems like there is some naming
conflict happening for THAllocator, which seems to be a bug.

**Comment by zdevito** [comment]
So I think what is happening is that 'THAllocator' gets defined both by Torch using ffi.cdef (probably inside `require 'torch'`) and inside the `terralib.includec`, which also internally calls ffi.cdef to register the type with the FFI, causing the 'redefine' message.

I added a workaround e2f99a9297, which just assumes the ffi definition for the type is the correct one. In this case, I think this is the correct behavior since it is just the same struct included in two different places. Let me know if that works for your purpose.

**Comment by alexbw** [comment]
Works great, thanks
