### ISSUE TITLE
Hint: Getting CUDA to work on Ubuntu Xenial

### ISSUE THREAD

**Issue by xspager** [zdevito/terra#174]
Great news (I think, might be useful to somebody), I got the CUDA tests to work on Ubuntu Xenial with the packaged version of the Nvidia stuff. I might forgoten a step but should't be very far from what I remember, here we go:

``` sh
$ sudo aptitude install clang-3.5 llvm-3.5-dev libclang-3.5-dev
$ sudo aptitude install nvidia-cuda-toolkit
```

now for the trick thanks to https://devtalk.nvidia.com/default/topic/936212/cuda-setup-and-installation/tensorflow-cannot-find-cudnn-ubuntu-16-04-cuda7-5-/post/4880549/#4880549

``` sh
sudo mkdir /usr/local/cuda
cd /usr/local/cuda
sudo ln -s  /usr/lib/x86_64-linux-gnu/ lib64
sudo ln -s  /usr/include/ include
sudo ln -s  /usr/bin/ bin
sudo mkdir nvvm
cd nvvm
sudo ln -s  /usr/lib/x86_64-linux-gnu/ lib64
```

might work with the linux binary release

**Comment by elliottslaughter** [comment]
FYI, we're setting up a new release here: #323. The Linux binaries are built with Ubuntu 16.04 and CUDA works.
