### ISSUE TITLE
Address sanitizer support

### ISSUE THREAD

**Issue by Lupus** [zdevito/terra#178]
Is it possible to add the ASAN instrumentation pass into terra? Low-level languages are really hard to debug when there are no tools available to validate memory management and check for leaks.

**Comment by Lupus** [comment]
@zdevito could you please share your opinion here? Is it at least feasible? What's the rough expectation on the amount of work if someone would try to do it?

So far we're using compilation to binary and valgrind, but it is slow and some cases are only feasible to debug with ASAN.

Thanks!

**Comment by zdevito** [comment]
I don't know enough about the ASAN pass to have an informed opinion. Can
you point me to the documentation about it, or at least the code? I agree
that it would be very useful to have if it were easy to add.

**Comment by Lupus** [comment]
I believe it's possible to just emit C function calls from the ASAN library [1] at certain points to mark memory reachable/unreachable and check if reads/writes are sane. I'll try to dig how Clang is doing that in more detail.

[1] https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/asan_interface.h

**Comment by Lupus** [comment]
It seems that the instrumentation is implemented here [1].

[1] http://llvm.org/docs/doxygen/html/AddressSanitizer_8cpp.html

**Comment by Lupus** [comment]
I've tried adding the following code to `llvmutil_optimizemodule()`:
```
     MPM.add(createAddressSanitizerFunctionPass(/*CompileKernel*/ false, false));
     MPM.add(createAddressSanitizerModulePass(/*CompileKernel*/false, false));
```

ASAN module constructor and some declarations appeared in the IR saved to file via `terralib.saveobj()` but actual instrumentation is not happening. May be that's the wrong place for it?

Clang is doing that a bit differently [1] though.

[1] https://github.com/llvm-mirror/clang/blob/5423d8c4fc3b8ba5756f2e16479552191d59e992/lib/CodeGen/BackendUtil.cpp#L184

**Comment by Lupus** [comment]
It seems that function pass manager does not do its job completely... @zdevito may be you have some ideas what might be wrong in this approach to integrate these llvm passes?

**Comment by zdevito** [comment]
I'll have to look into it more, it is possible that the code generation
pass also needs to know that you want the ASAN modifications enabled, but I
don't have any experience using it and my impression from using other LLVM
functionality is that it is normally necessary to read through the code of
a working example (e.g. clang) to figure out how it needs to be run.

**Comment by Lupus** [comment]
Hey @zdevito, did you have a chance to look into this?

**Comment by zdevito** [comment]
I did some experiments with it. It is only a couple lines to add the right
annotations and the right LLVM passes, but it is a bit tricky to package it
correctly with the .dylib that need to mock out malloc/free. I think it
will work. One tricky bit is getting the right stack trace information
registered in a way that the stack traces generated by the sanitizer know
about Terra functions, otherwise you get very cryptic messages when
something fails. I have to revisit it since the story behind debug info for
LLVM JIT compilation has improved over time.

**Comment by Lupus** [comment]
Thanks for an update, sounds promising! Having ASAN on board will make terra even more attractive for system software developers.

**Comment by Lupus** [comment]
Hey @zdevito!

How's your rework of LLVM debug information going? I believe I've seen a lot of commits related to this.

If I understand it correctly, debug information and asan runtime library link are two blockers for asan support. Is my understanding correct?

Thanks!

**Comment by elliottslaughter** [comment]
@Lupus Are you still interested in this?

**Comment by Lupus** [comment]
Hey, unfortunately I'm no longer interested in terra, feel free to close if
no one else needs this.

пн, 3 дек. 2018 г., 23:13 Elliott Slaughter notifications@github.com:
