### ISSUE TITLE
Function list

### ISSUE THREAD

**Issue by rokf** [zdevito/terra#181]
Is there a list of all added functions or a way to get one?

I'm writing a Terra bundle(extension) for http://howl.io/ and I'd like to add autocomplete functionality similar to ctags.

I've been thinking about running through tables with iterators and gaining the name and type of functions and variables that way. However I don't get any descriptions that way and not everything will be listed probably.

There is quite a lot of data so I wouldn't do it all manually if possible.

**Comment by zdevito** [comment]
Like Lua functions, Terra functions are first-class Lua objects that can live anywhere in the Lua environment of the program. So there isn't a global list of functions like there isn't a list of Lua functions.
