### ISSUE TITLE
Cast from anonymous struct doesn't invoke __cast metamethod

### ISSUE THREAD

**Issue by elliottslaughter** [zdevito/terra#188]
I discovered recently that a cast from an anonymous struct (e.g. `{1, 2, 3}`) to some type with a `__cast` metamethod does not invoke that type's `__cast` method. This means, for example, that it is impossible to write a transitive `__cast` method via another type (which would allow that cast). Consider the following code:

```
struct a {
  x : int,
  y : int,
  z : int,
}

struct b {
  impl : a,
}
local function can_cast(from, to)
  local function test()
    local v = terralib.newsymbol(from)
    return (`([to]([v]))):gettype()
  end
  local valid = pcall(test)
  return valid
end
b.metamethods.__cast = function(from, to, expr)
  if can_cast(from, a) and to == b then
    return `([to]{ impl = [expr] })
  else
    error()
  end
end

-- With the above __cast method, we can cast from a to b and from a
-- tuple to a, but **NOT** from a tuple to b.
print("can_cast(a, b)", can_cast(a, b))
print("can_cast({int, int, int}, a)", can_cast(terralib.types.tuple(int, int, int), a))
print("can_cast({int, int, int}, b)", can_cast(terralib.types.tuple(int, int, int), b))

-- This means that b cannot be constructed from an anonymous struct:
terra main()
  var x = a { 1, 2, 3 }
  var y = [b](x) -- So this works.
  var z = [b]({ 4, 5, 6 }) -- But this doesn't.
end
main()
```

This produces the following output, and then hits a type error from the cast failure in main.

```
can_cast(a, b)  true
can_cast({int, int, int}, a)    true
can_cast({int, int, int}, b)    false
```

(I use transitive casts like this in Regent when I construct types which wrap other types, but I still want to be able to construct them from anonymous structs like the original type.)

**Comment by zdevito** [comment]
The reason anonymous structs do not respect __cast is because they are used to actually construct new structs.  `Foo { a = 4, b = 3}` is a cast of the anonymouse strict `{ a= 4,b=3}` to `Foo`. I am trying to think if there is a way to disambiguate this case.

**Comment by elliottslaughter** [comment]
I believe the reason why it's failing to disambiguate is that https://github.com/zdevito/terra/blob/master/src/terralib.lua#L2251 returns immediately rather than falling through to `insertcast` (which contains the logic for `__cast`). If you continued on failure rather than returning, then you could try both the structural and user-defined casts.

(There is a similar check at https://github.com/zdevito/terra/blob/master/src/terralib.lua#L2190 but I believe it is not an issue because it checks `convertible` on both types; therefore the destination type cannot be a user-defined struct.)

**Comment by zdevito** [comment]
I think trying to allow both casts here and preferring the user-defined
one (or vice versa)  can lead to some surprising behavior where an overly
permissive user-defined cast basically shadows the default cast, making it
hard to actually construct an object of the the type. Normally in Lua and
Terra when an operation is already defined the user is not able to override
it (e.g. pointer arithmetic, assignment). I'll think more about ways of
making object construction and object casting distinct operations to try to
get this two potential uses disambiguated but I am not a fan of having the
compiler try to decide for you.
