### ISSUE TITLE
Can't use shared or static libraries on Linux when using saveobj

### ISSUE THREAD

**Issue by 0joshuaolson1** [zdevito/terra#193]
From https://mailman.stanford.edu/pipermail/terralang/2016-July/000517.html :

I looked through https://github.com/zdevito/terra/blob/master/src/terralib.lua but can't find the environment variables being used to search. `terralib.includec` finds all the symbols I need from `/usr/local/include`, but `/usr/local/lib[64]` is where the static and shared libraries are and both JIT and `saveobj` spit this at me:
```
LLVM ERROR: Program used external function '[irrelevant]' which could
not be resolved!
```
I'm not on an Ubuntu-based distro. Where should I move them?

**Comment by zdevito** [comment]
The symbols need to be linked in to the process before Terra can find them.
You can do that by calling `terralib.linklibrary()` which will internally
dlopen the libraries so that LLVM can find them. The library search path
works the same as dlopen()

**Comment by 0joshuaolson1** [comment]
Thank you. `linklibrary`'s [documentation](http://terralang.org/api.html#c-backwards-compatibility) says this is necessary when `includec`'d headers' declarations' definitions are not linked into the executable in which Terra is run, and

>this situation arises when using external libraries with the terra REPL/driver application.

So is there a way to link to my static library using `saveobj`? Is dynamic loading just for the compilation phase?

**Comment by 0joshuaolson1** [comment]
I changed the name because in addition to my previous question,

> is there a way to link to my static library using saveobj? Is dynamic loading just for the compilation phase?

Terra can JIT my code, which is currently using a shared library, but attempting `saveobj` results in this message:
```
/tmp/terra-ab4f0d.o: In function `main':
terra:(.text+0xc): undefined reference to `soundio_create'
terra:(.text+0x25): undefined reference to `soundio_connect_backend'
terra:(.text+0x30): undefined reference to `soundio_strerror'
terra:(.text+0x5a): undefined reference to `soundio_flush_events'
terra:(.text+0x62): undefined reference to `soundio_output_device_count'
terra:(.text+0x86): undefined reference to `soundio_get_output_device'
terra:(.text+0xaa): undefined reference to `soundio_strerror'
terra:(.text+0xd4): undefined reference to `soundio_device_unref'
terra:(.text+0xec): undefined reference to `soundio_outstream_create'
terra:(.text+0x10a): undefined reference to `soundio_outstream_open'
terra:(.text+0x115): undefined reference to `soundio_strerror'
terra:(.text+0x14d): undefined reference to `soundio_strerror'
terra:(.text+0x164): undefined reference to `soundio_outstream_start'
terra:(.text+0x16f): undefined reference to `soundio_strerror'
collect2: error: ld returned 1 exit status
llvm: 

stack traceback:
	[C]: in function 'saveobj'
	src/terralib.lua:3979: in function 'saveobj'
	dactile.t:67: in main chunk
```
My program looks like:
```
C = terralib.includec("stdio.h")
C.strcmp = terralib.includec("string.h").strcmp
Sio = terralib.includec("/home/sideburnetic/0sio1/soundio/soundio.h")
terralib.linklibrary("/home/sideburnetic/0sio1/build/libsoundio.so")
terra main()
...
end
--main()
terralib.saveobj("dactile", {main = main})
```

**Comment by zdevito** [comment]
You can specify linker flags using saveobj to make link against the
library. Something like:

terralib.saveobj("dactile", {main = main},
{"-L","/home/sideburnetic/0sio1/build","-l","soundio"})

**Comment by 0joshuaolson1** [comment]
Ugh, you mean I have to learn something? ;) I'll close this when I get dynamic and static working.

**Comment by 0joshuaolson1** [comment]
Interestingly, `terralib.saveobj("dactile", {main = main},
{"-L","/home/sideburnetic/0sio1/build","-l","soundio"})` almost works. I can run code that uses the library, but one of the later library functions returns an error code instead of opening my sound card like the identical JITted code.

**Comment by 0joshuaolson1** [comment]
Woo, even links with a static build. Sorry for the dumb issue.
