### ISSUE TITLE
Closures/nested terra function definitions

### ISSUE THREAD

**Issue by 0joshuaolson1** [zdevito/terra#195]
```
> print((terra() return (terra() return -2 end)() end)())
[string "stdin"]:1: nested terra functions cannot be nested in terra functions. near 'terra'
```

**Comment by zdevito** [comment]
Not right now. It requires a concept of closures which can be tricky to get
working without automatically managed memory.

**Comment by 0joshuaolson1** [comment]
Makes sense. I'm just trying to keep callback definitions close to their use, which don't need Terra value capturing but instead require unnecessary function naming.

**Comment by Lupus** [comment]
Clang blocks [1] can be used as a source of inspiration. Blocks are first class objects and need explicit release.

[1] http://clang.llvm.org/docs/BlockLanguageSpec.html

**Comment by elliottslaughter** [comment]
@0joshuaolson1 Are you still interested in this?

**Comment by 0joshuaolson1** [comment]
No. Note that pure functions don't need closures.

**Comment by capr** [comment]
Actually you don't have to implement full Lua-style closures with heap-based writable upvalues. 

I think a limited form of closures based on LLVM trampolines would be sufficient for all those cases where C sucks with callbacks. These types of closures would also _work with existing C libraries._

**Comment by capr** [comment]
@elliottslaughter if you're still interested if I'm interested, I am interested in this :)

**Comment by aiverson** [comment]
This can sort of be done already. Example using my filter-map-reduce library:

```
print(intrange(1, 100):filter([terra (a: int) return a % 2 end]):map([terra (a: int) return a * a end]):reduce([terra(a: int, b: int) return a + b end]))
```

**Comment by capr** [comment]
In many cases you need to close on some variables from the surrounding scope to do anything useful. Besides, eve these contrieved examples would look better to my eyes with just a `for` and an `if` and you wouldn't be painting yourself into a corner with what you can do (since you _can_ access the entire lexical scope with a `for` construct but you can't with this style).
