### ISSUE TITLE
Set operation libraries

### ISSUE THREAD

**Issue by konobi** [zdevito/terra#202]
There doesn't seem to be a good place for discussion other than the issues list, so I'm posting here.

Does anyone one have a library/implementation of set operations for terra, that work in lua and are portable to other terra based languages?

**Comment by 0joshuaolson1** [comment]
It seems not.

**Comment by cinterloper** [comment]
you might be able to use the c interface of tds inside of terra, and its lua interface, in lua, and pass back and forth through serialization

https://github.com/torch/tds

**Comment by elliottslaughter** [comment]
@konobi Are you still interested in this?

**Comment by elliottslaughter** [comment]
For future reference, we're trying to push stuff like this to here: https://github.com/terralang/std
