### ISSUE TITLE
Addition of lcpp for use when loading c headers

### ISSUE THREAD

**Issue by konobi** [zdevito/terra#203]
I was reading through the thesis paper and noted that lack of cpp support with ffi was lacking so some automate-able stuff wasn't possible. I've noted that there's now a somewhat transparent way of adding cpp support to ffi that works for both lua and luajit:  http://lcpp.schmoock.net/

**Comment by konobi** [comment]
I could submit a PR, since it's fairly simple, but it's probably the sort of thing that needs hooked in to be effective. Do you have a preference?

**Comment by zdevito** [comment]
I haven't had time to look into this yet.  Some of our C code goes through
the Clang preprocessor rather than through LuaJIT's, which might make this
more complicated to integrate, potentially.

**Comment by konobi** [comment]
There was only one additional failing test when I hooked it in and ran the test suite. That seemed related to bytecode serialization, i think, so it mightn't be too far off already. =0)

**Comment by elliottslaughter** [comment]
@konobi Are you still interested in this?
