### ISSUE TITLE
terralib.saveobj and global variables

### ISSUE THREAD

**Issue by Lupus** [zdevito/terra#204]
I'm using golike.t for interfaces, and when I saved the main function into an executable with the below snippet, I got a segmentation fault.
```terra
terralib.saveobj("run_tests", "executable", {
        main = run_tests
}, {"some", "linker", "flags"})
```

It crashes at [this point](https://github.com/zdevito/terra/blob/f4201e2cf5208a158d773cfa79a45354db674217/tests/lib/golike.t#L53):

```terra
return  m.type(self.vtables[id].[m.name])(obj,[m.syms])
```

I've instrumented this point with some debugging printf's:

```terra
S.fprintf(S.stderr, "vtables: %p\n", self.vtables)
S.fprintf(S.stderr, "vtables[%d]: %p\n", id, self.vtables[id])
S.fprintf(S.stderr, "vtables[%d].[%s]: %p\n", id, m.name, self.vtables[id].[m.name])
```

And here's what I got:

```
vtables: (nil)
Segmentation fault
```

Is it possible to include the vtables global variable into the resulting binary?

```terra
self.vtables = global(&self.vtabletype)
```

How terra tracks dependencies between pieces of code when dumping them into a binary?

P.S.: I want to save my test runner into a binary so as to validate it with valgrind. Along with debug information enabled, it is a great way to ensure no memory problems exist.

**Comment by Lupus** [comment]
Looks like it's related to [1]. Is the issue due to lack of support for constant expressions?

[1] https://mailman.stanford.edu/pipermail/terralang/2013-November/000317.html

**Comment by zdevito** [comment]
At the time I wrote the golike.t example, it wasn't possible to actually
save/reload the code because it requires you to save the function pointers
that implement each instance of interface, which are different on every
load of the program. I've since added the ability to create constant
expressions that can contain function pointers, but I haven't had time to
update the vtable in the golike example to use it yet.

**Comment by Lupus** [comment]
Sounds cool! How is it possible to use constant expressions for golike? Interface is first registered, and fixed size array of vtables is allocated. Then it is filled on demand when something is being cast to an interface.

I was thinking of dumping all the vtables into some initializer function, which would reconstruct them at runtime (same can be done with constant expressions probably), and then call this function before any other code in the resulting binary.

**Comment by Lupus** [comment]
Never mind, I figured it out. I've extended interface type to hold two pointers --- one for the constant expression with function pointers and another one is the pointer to self (actual object). During the cast metamethod I create new vtable implementation as a constant expression and cache it for subsequent use. The dynamic array of implementations is not needed any more in this case.

**Comment by zdevito** [comment]
Good! If you have example code that works with saveobj, I can include it in
the test programs of Terra so that others can see it.

**Comment by Lupus** [comment]
I've created #206 for this, @zdevito please take a look.

**Comment by zdevito** [comment]
Thanks!
