### ISSUE TITLE
Possible to return via macro from parent scope --- intended?

### ISSUE THREAD

**Issue by Lupus** [zdevito/terra#208]
I've ran into an interesting case accidentally, instead of returning `quote ... in ... end` I returned `quote ... return ... end`, and this resulted in return appearing in my function calling the macros. Minimal test case:

```terra
local S = require("std")

local get_out = macro(function()
        return quote
                return
        end
end)

terra test_this_macro()
        S.printf("point A\n")
        get_out()
        S.printf("point B\n")
end

test_this_macro:printpretty()
test_this_macro:disas()
```

Output:

```
./tests/talloc.t:42:    terra test_this_macro() : {}
./tests/talloc.t:43:        printf("point A\n")
./tests/talloc.t:39:        return
./tests/talloc.t:45:        printf("point B\n")
./tests/talloc.t:42:    end
definition      {} -> {}

define void @"$test_this_macro"() #0 {
entry:
  %puts = tail call i32 @puts(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str, i64 0, i64 0))
  ret void
}

assembly for function at address 0x7fa17a591000
0x7fa17a591000(+0):             push    rbp
0x7fa17a591001(+1):             mov     rbp, rsp
0x7fa17a591004(+4):             movabs  rdi, 140331519115264
0x7fa17a59100e(+14):            movabs  rax, 140331496119856
0x7fa17a591018(+24):            pop     rbp
0x7fa17a591019(+25):            jmp     rax
```

I was wondering if this is an expected behavior? It feels more like C with ability to inject arbitrary code than hygienic terra approach.

**Comment by zdevito** [comment]
This is expected. Like LISP macros, Terra macros are really just ways of piecing code together.  Being able to return from a macro is useful, for instance, for error handling where a macro can check and error code, report the error, and return from the surrounding function in a single macro.

**Comment by Lupus** [comment]
I agree, that's awesome. Just wanted to ensure it's not some sort of undocumented behavior :)

May be it's possible to get the type for the surrounding function from within a macro?
