### ISSUE TITLE
question: how to use a return value from a Lua function

### ISSUE THREAD

**Issue by chrisranderson** [zdevito/terra#210]
This issue may not be related to Terra, and actually related to the library I'm using - I'm sorry if that's the case! Here is a stubbed version of my Lua function (same return type and error with my actual code):

```
local get_image_difference = function (start_width, start_center, horizon_height, end_width, end_center)
    return 9999
end
```

And the Terra function that calls it:

```
terra()
   -- some other stuff before this
    var difference = get_image_difference(start_width, end_center, horizon_height, end_width, start_center)

    qs.factor(difference)
end
```

And finally the error that I get:

```
/home/chris/quicksand/qs/progmodule.t:43: Errors reported during compilation.
road-match.t:108: invalid conversion from {} to double
    qs.factor(difference)
                       ^
road-match.t:108: previous errors occurred while typechecking this macro
    qs.factor(difference)
             ^

stack traceback:
    [C]: in function 'error'
    src/terralib.lua:446: in function 'finishandabortiferrors'
    src/terralib.lua:516: in function 'gettype'
    /home/chris/quicksand/qs/progmodule.t:43: in function 'fn'
    src/terralib.lua:1193: in function 'progcompile'
    /home/chris/quicksand/qs/progmodule.t:52: in function 'compile'
    /home/chris/quicksand/qs/trace.t:919: in function 'RandExecTrace'
    /home/chris/quicksand/qs/mcmc.t:47: in function 'method'
    /home/chris/quicksand/qs/infer.t:61: in function 'infer'
    road-match.t:116: in main chunk
```

I want to use the value returned from Lua code (which uses Torch tensors to compute the return value) in my Terra function. I read the section in the docs titled "Converting Lua values to Terra values of known type" but I don't understand what it is suggesting that I do. 

Thanks for reading and the help!

**Comment by OvermindDL1** [comment]
As I recall, terra cannot deduce the return type of a lua function so you basically need to 'cast' it to tell it both what it should be and so that it should fail if it does not match it.  `get_image_difference:peektype()` would probably tell you what it thinks the return type is (being lua it defaults to {} unless you've specifically annotated it, which has not been shown in the above example).

Thus I think you did not annotate the lua function return type?  I think that is `terralib.cast` if I recall correct.

/me is newish with Terra.

**Comment by chrisranderson** [comment]
Not much success with `peektype`. 

How do you annotate a Lua function? 

Also, I've tried this:

```
var difference = [int8](get_image_difference(start_width, end_center, horizon_height, end_width, start_center))
```

But I get an error:
```
src/terralib.lua:575: Errors reported during compilation.
road-match.t:106: invalid conversion from {} to int8
    var difference = [int8](get_image_difference(start_width, end_center, horizon_height, end_width, start_center))
                                                ^
road-match.t:106: previous errors occurred while typechecking this macro
    var difference = [int8](get_image_difference(start_width, end_center, horizon_height, end_width, start_center))
                           ^

stack traceback:
	[C]: in function 'error'
	src/terralib.lua:446: in function 'finishandabortiferrors'
	src/terralib.lua:516: in function 'gettype'
	src/terralib.lua:575: in function 'addvalue'
	src/terralib.lua:580: in function 'jitvalue'
	src/terralib.lua:595: in function 'compile'
	/home/chris/quicksand/qs/progmodule.t:17: in function 'fn'
	src/terralib.lua:1193: in function 'typeDetectionPass'
	/home/chris/quicksand/qs/progmodule.t:33: in function 'fn'
	src/terralib.lua:1193: in function 'progcompile'
	/home/chris/quicksand/qs/progmodule.t:52: in function 'compile'
	/home/chris/quicksand/qs/trace.t:919: in function 'RandExecTrace'
	/home/chris/quicksand/qs/mcmc.t:47: in function 'method'
	/home/chris/quicksand/qs/infer.t:61: in function 'infer'
	road-match.t:116: in main chunk
```

**Comment by OvermindDL1** [comment]
Oh right, meant to link to that.  ^.^

It is in the Getting Started Guide:  http://terralang.org/getting-started.html#lua-terra-interaction
Specifically it states:
> since we cannot determine the Terra types that function will return, Lua functions do not return values to Terra functions by default. To convert a Lua function into a Terra function that does return a value, you first need to cast it to a Terra function type:
> ```lua
> function luaadd(a,b) return a + b end
> terraadd = terralib.cast( {int,int} -> int, luaadd)
>  
> terra doit()
> 	return terraadd(3,4)
> end
> ```

**Comment by chrisranderson** [comment]
Yay! Thank you, that works great. Hopefully googlers will find this thread if they have the same issue. I was reading only in the API reference - I guess I expected it to be comprehensive. That works perfectly (except for adding `local` to the definition of `terraadd`).

**Comment by OvermindDL1** [comment]
Yeah I want not able to find that important bit of information in the API Reference either, perhaps that needs an update?

**Comment by zdevito** [comment]
Just got to this now, I have to do a large update to the docs to explain
this behavior better. The suggested solution is the right way to do it.

**Comment by cl4ws0n** [comment]
Is there not a way to return a string from a lua function to terra? I tried various casts but always get an error that it cannot convert string

**Comment by cl4ws0n** [comment]
Likewise, how would you convert a cdata<char *> back into a lua string?

**Comment by elliottslaughter** [comment]
@chrisranderson Are you still interested in this? If so you could try again on master? I'm trying to figure out which of the older issues are still relevant.
