### ISSUE TITLE
No terralib.includec("stdio.h").EOF

### ISSUE THREAD

**Issue by 0joshuaolson1** [zdevito/terra#213]
Macros that are simple constants are supposed to work, right?

**Comment by bananu7** [comment]
Are you sure that your `stdio.h` physically contains this definition? Out of curiosity, I've checked a few instances of that file on my machine, and found one in Chef's DevKit i686-w6-mingw32 that has something like that:

```
#include <ssp.h>
#include_next <stdio.h>
```

Those files are, in principle, specific to the compiler; IIRC the C standard doesn't require them to be files at all.

**Comment by 0joshuaolson1** [comment]
I haven't found a copy of an official C library spec, but all of the following claim that EOF is defined by importing stdio:

http://www.glue.umd.edu/afs/glue.umd.edu/system/info/olh/Programming/C_Programming_on_Glue/The_Third_C_Program_Character_Data/eof_stdio
http://en.cppreference.com/w/cpp/io/c
https://www-s.acm.illinois.edu/webmonkeys/book/c_guide/2.12.html#variables
http://www.di-mgt.com.au/docs/CStdLib.html

I wouldn't expect Clang to be the odd one out.

**Comment by jakwings** [comment]
I don't find the imported symbol too (terra with llvm-3.9.0 on osx). But the included C code has it:

```terra
C = terralib.includecstring([[
#include <stdio.h>

int eof()
{
    return EOF;
}

int main(void)
{
    return fprintf(stdout, "%d\n", eof());
}
]])

terra main()
  var length : int = C.main()
  --return length == C.printf("%d\n", C.EOF)
  return length == C.printf("%d\n", C.eof())
end

terralib.saveobj("hello", {main = main})
```

**Comment by 0joshuaolson1** [comment]
This is a duplicate of #219. Line 90 of https://www.gnu.org/software/m68hc11/examples/stdio_8h-source.html defines EOF with a parenthesized -1.
