### ISSUE TITLE
Can I write a kernel in Terra or not?!

### ISSUE THREAD

**Issue by Izrab** [zdevito/terra#216]
This is the third time I am asking, but no one is answering at all!

**Comment by zdevito** [comment]
I am not sure how to answer your question. Terra can generate C ABI compatible code, and doesn't require its own runtime. So it is suitable for things like embedded computing where those things are not available. Presumably, you could write an entire kernel in it, but I don't think anyone has tried yet, so it is likely you will hit some corner cases where you need low-level access to some features.
