### ISSUE TITLE
Building on Gentoo

### ISSUE THREAD

**Issue by JohnMH** [zdevito/terra#218]
From what I've seen, the build goes well until this step. I haven't looked much into what's calling this yet, but if anyone has any ideas as to how to fix this, I'd be more than happy to give some things a try.

```
# extract needed LLVM objects based on a dummy linker invocation
< build/llvm_objects/llvm_list build/bin/luajit-2.0.4 src/unpacklibraries.lua build/llvm_objects
ar: invalid option -- 'n'
```

**Comment by elliottslaughter** [comment]
If you're still interested in this, can you please try the master branch? There are two things to try:

 1. the Makefile, as before
 2. CMake

The latter is experimental but works better in some cases.

Note also that we've got support for LLVM 5 and 6 now.

**Comment by elliottslaughter** [comment]
I'm closing this since there hasn't been much activity, but I think if you tried CMake on a recent version of Terra you'd be pleasantly surprised. At least in the testing I've done it has been much more robust.
