### ISSUE TITLE
Wasm32 `target` in saveobj?

### ISSUE THREAD

**Issue by cinterloper** [zdevito/terra#225]
https://gist.github.com/yurydelendik/4eeff8248aeb14ce763e

I tried to follow this guide to create some Web Assembly from Terra code via bitcode, but realized they have a special wasm32 target

could you shed some light on what it would take to get Terra to emit wasm32 format assembly?

Thanks in advance for this cool project

**Comment by zdevito** [comment]
In theory it supports cross compilation (
http://terralang.org/api.html#targets), but you will need to build against
a version of LLVM that has the wasm32 target, which I believe is pretty
new.

**Comment by cinterloper** [comment]
OK, I see now that it did not get added to llvm untill 3.8
https://reviews.llvm.org/rL246814

I will try a Terra built against llvm 3.8 with web assembly enabled, and reopen this if I find some issue.
