### ISSUE TITLE
Compiling with gcc 5.1.*

### ISSUE THREAD

**Issue by lightsighter** [zdevito/terra#226]
Just an FYI for everyone trying to compile Terra with gcc 5.1.*, you are likely to run into linker errors when attempting to link against any pre-built LLVM/clang libraries due to this current LLVM bug:

https://llvm.org/bugs/show_bug.cgi?id=23529

Switching back to gcc 4.* seems to fix the issue for now.  In the future there should be a version of the LLVM/clang libraries that support gcc 5.1.* but not yet.

**Comment by elliottslaughter** [comment]
I'm closing this for now since most people will have moved off of GCC 5.1. We also have support for newer LLVM versions that shouldn't have this problem even with the old GCC version.
