### ISSUE TITLE
Compile problems

### ISSUE THREAD

**Issue by HollisJoe** [zdevito/terra#233]
Hi！ What kind of question is that？ Thanks！
![default](https://cloud.githubusercontent.com/assets/24452259/24195879/691a1930-0f36-11e7-8f67-1627722243f7.png)

**Comment by HollisJoe** [comment]
This can be compiled on VS2010？

**Comment by zdevito** [comment]
This is bug in the Windows nmake file where it doesn't handle spaces in the
path to LLVM correctly. I don't have a windows machine at hand to debug it,
but a workaround might be to move LLVM to somewhere without spaces.

**Comment by HollisJoe** [comment]
I don't find the file build\clangpaths.h:
![default](https://cloud.githubusercontent.com/assets/24452259/24337594/7a50b0a8-12d1-11e7-898e-21df3156f2fd.png)
It's this reason?

**Comment by HollisJoe** [comment]
YES! This is the problem! Thank you! and I have to compile the CLANG and LLVM?
