### ISSUE TITLE
Some Errors for execute

### ISSUE THREAD

**Issue by HollisJoe** [zdevito/terra#234]
Hi! Program is a compilation of my own, I installed LLVM3.5 and compiled a CLANG and LLVM, I tested the program compiled without problems, but implementation has the following problem. What is the situation?
![Uploading 图片.png…]()

**Comment by bananu7** [comment]
Your screenshot looks broken, at least on my end (doesn't display).

**Comment by elliottslaughter** [comment]
I'm closing this for now, but if you want more help please feel free to respond and let us know what issues you're hitting.
