### ISSUE TITLE
autograd implementation

### ISSUE THREAD

**Issue by FongHou** [zdevito/terra#237]
Hi,

I've been using terra with torch for a while. They work nicely together (yeah tab complete terra objects in repl :)

I'm curious whether terra has a reverse-mode autograd implementation like https://github.com/twitter/torch-autograd. Since terra excels at meta-programming, it seems a good fit for that. Would its performance beat torch-autograd? even beat a C++ implemenation (pytorch recently took the spotlight by rewriting autograd in C++).

I'm not knowledgable enough on the topic, just reading below raised some curiosity.

https://en.wikipedia.org/wiki/Automatic_differentiation#Source_code_transformation_.28SCT.29
http://www.sciencedirect.com/science/article/pii/S0377042700004222

Thanks!

**Comment by 0joshuaolson1** [comment]
There are three things that C++ does better than Terra:
- portability
- non-metaprogramming optimizations
- intrinsics

But Terra can do practically everything a Lua interpreter can do, so that library is just inefficient Terra.

**Comment by elliottslaughter** [comment]
I'm closing this since it's not directly related to a Terra feature or bug, and also hasn't seen activity recently. Please feel free to reopen if you feel there is more to discuss here.
