### ISSUE TITLE
LLVM >3.5 support

### ISSUE THREAD

**Issue by parasange** [zdevito/terra#241]
Are there any plans to make Terra compatible for LLVM/Clang >3.5?
I'm trying to build it with LLVM 3.8, but it does not seem to work.

**Comment by zdevito** [comment]
It should work with LLVM up to version 3.9. Currently the recommended version is LLVM 3.8, since it is the only one that will work with modern CUDA installs, and I've added more support for debug info in that version.

**Comment by parasange** [comment]
Sorry, my fault of not specifying the problem further.
Had some undefined reference linker issues that I for now fixed with that hint coming from 
@paniq in #131 by changing the line 
`CPPFLAGS += -std=c++11` to `CPPFLAGS += -std=c++11 -Wno-c++11-narrowing -D_GLIBCXX_USE_CXX11_ABI=0`
