### ISSUE TITLE
build terra failure

### ISSUE THREAD

**Issue by mxgbs** [zdevito/terra#252]
Hi,

Since terra not work even when I add C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC to the environment variable, I start to build that from scratch. However, following error occurs:
C:\Users\dengya\Downloads\terra-master\terra-master\msvc>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cd C:\Users\dengya\Downloads\terra-master\terra-master
        C:\Users\dengya\Documents\LuaJIT\LuaJIT-2.0.5\src\luajit.exe src\genclangpaths.lua build\clangpaths.h C:\Program Files\LLVM\bin\clang -I "CC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include"
C:\Users\dengya\Documents\LuaJIT\LuaJIT-2.0.5\src\luajit.exe: src\genclangpaths.lua:13: assertion failed!
stack traceback:
        [C]: in function 'assert'
        src\genclangpaths.lua:13: in main chunk
        [C]: at 0x7ff6cc984f00
NMAKE : fatal error U1077: 'C:\Users\dengya\Documents\LuaJIT\LuaJIT-2.0.5\src\luajit.exe' : return code '0x1'

Can someone help me with this? Thank you.

If you can provide a way to have the release version running on windows 10 with VS2015 installed, that would be really appreciated.

**Comment by elliottslaughter** [comment]
New binaries are here: #323

Please let us know if you have any other issues.

**Comment by DemonCyborg** [comment]
https://github.com/Mx7f/llvm-package-windows/releases/download/clang-6.0.1-nvptx/llvm-6.0.1-windows-amd64-msvc14-msvcrt.7z
