### ISSUE TITLE
Bug Bounty program

### ISSUE THREAD

**Issue by Chokoabigail** [zdevito/terra#254]
Is there a Bug Bounty program?
If so where can I find more details about her?
(More details = what bugs are accepted, what is the minimum payment, what form of submission accepted , who to submit my founding, etc.)

**Comment by elliottslaughter** [comment]
Typically, a bug bounty program would be offered by a company, and I'm not presently aware of any companies supporting Terra in this way. (But if you know of any, please say so.)

**Comment by elliottslaughter** [comment]
I'm closing this for now, but if anyone has knowledge of a bug bounty program that would cover Terra, feel free to reply here.
