### ISSUE TITLE
Using macros with statements

### ISSUE THREAD

**Issue by multigrid101** [zdevito/terra#255]
I'll say up front that this is just a minor problem, but it's been bugging me for months now........
When I try to use macros with statements as arguments, I get an error, e.g.

```lua
C = terralib.includecstring[[
#include <stdio.h>
]]

-- A macro like this would be useful to e.g. time sections of code
foo = macro(function(stmt)
return quote
   C.printf("start\n") 
   [stmt]
   C.printf("stop\n") 
end
end)


terra doit()
  foo(3+4) -- WORKS

  -- var a : int
  -- foo(a = 3+4) -- DOESN'T WORK
end
print(doit)
```
Calling `foo(3+4)` works and calling `foo(a=3+4)` throws an error. I can, of course, work around this issue e.g. as follows:

```lua
foo2 = function(stmt)
return quote
   C.printf("start\n") 
   [stmt]
   C.printf("stop\n") 
end
end


terra doit2()
  var a : int
  [foo2(quote a = 3+4 end)]
end
print(doit2)
```
i.e. by
* defining a lua-function instead of a macro
* escaping the function-call and quoting the args explicitly

Is there any other way to achieve this without a workaround? It's really just a bit of extra work on the keyboard but would be nice if I could avoid it.

**Comment by elliottslaughter** [comment]
You could write a language extension (http://terralang.org/api.html#embedding-new-languages-inside-lua), but aside from that I'm not aware of any way to do this. Unlike say, Common Lisp, where the arguments to macros are uninterpreted, I believe the arguments to macros in Terra need to parse (and possibly even type check) as expressions (i.e. as if the macro were a function call).

**Comment by multigrid101** [comment]
Thanks for the info, I guess I'll just have to live with the work-around then :)
