### ISSUE TITLE
LLVM version

### ISSUE THREAD

**Issue by mxgbs** [zdevito/terra#256]
@elliottslaughter 
Hi,
The released version not work with cuda, Documents\Optlang\terra\bin>terra ..\share\terra\tests\cudatest.t
C:\Users\zdevito\terra\src\tcuda.cpp:139: nvvm error reported (7)
 libnvvm : error: -arch=compute_61 is an unsupported option .
And the released  version only can be used with CUDA 7.5 which doesn't support 61 architecture. I think I can only build terra from scratch. I'm wondering if your current project supports any 3.70+ version of LLVM? LLVM only have 64bits version after 3.7.0.

**Comment by elliottslaughter** [comment]
Terra currently supports up to LLVM 3.9. However, I believe that it is recommend that you use an LLVM version that matches the NVVM version you are using. So if you are using NVVM 3.8 you should use LLVM 3.8.

I unfortunately don't know anything about how the release binaries were built, so I'm not sure I can't say much about those.
