### ISSUE TITLE
Can't build terra if llvm+clang is self-built

### ISSUE THREAD

**Issue by multigrid101** [zdevito/terra#257]
Hi there,

I faced a problem while building terra with a version of `llvm` and `clang` that I compiled myself. Note that I used clang and llvm 3.5.0 and also managed to "solve" the problem. Mainly, i'd like to know if I encountered a bug or made mistakes during compilation.

Side Note: The pre-built binaries/libs for clang and llvm 3.5.0 were not an option for me as during compilation I encountered some "undefined reference" errors, probably because the pre-built stuff is for ubuntu 14.04 and I am using 16.04. I have faced this issue several times before with other libraries that were built with the "wrong" platform or compiler-version so I assume that it will be an issue for other people in the future (that is, people who want to build terra by themselves).

Side Note 2: I encountered a minor issue while building clang and llvm, which can be fixed as described [here](http://lists.llvm.org/pipermail/llvm-bugs/2014-July/034874.html). I am just mentioning this for reference.

I followed the build-instructions for terra in the readme and the build-instructions for clang and llvm from [here](http://clang.llvm.org/get_started.html). When compiling terra (after compiling clang and llvm), the compiler complains about

1.  The `clang` include files being in the wrong location
2. (after fixing (1)) some missing `*.inc` files

I managed to get everything working by manually copying files (and changing some directory-locations) inside my self-built llvm/clang directory. The exact steps are quite obvious when looking at the compiler errors (during terra compilation)

So for now my question is: Is this a bug or did I mess up during compilation?

regards

**Comment by elliottslaughter** [comment]
This is probably a bug. In general Terra's build system tends to be brittle, and LLVM is complex to build against. Specifically:

 1. I've had issues building on Ubuntu 16.04 with the version of LLVM/Clang from the official repos.
 2. I've had issues in some cases when LLVM is built with CMake. (#235)

I haven't tried using the binaries from llvm.org in a long time, but I definitely wouldn't expect those to work out of the box if they're compiled on earlier version of Ubuntu. The GCC on Ubuntu 16.04 is GCC 5, which also causes issues (#226) those these ones are GCC's fault.

If you can determine what went wrong, and if there are sensible fixes we can put into the Makefile to make it more robust, I think we'd be happy to accept them.

**Comment by OvermindDL1** [comment]
Well if the build system is switched to CMake then you could use the [hunter](https://docs.hunter.sh/en/latest/index.html) dependency system (pure CMake based) to pull the exact [llvm](https://docs.hunter.sh/en/latest/packages/pkg/LLVM.html) (it has options for pulling a specific version as well) you want, then you just link it into your using the standard CMake `target_link_library(terra llvm)` command and everything gets built and linked in properly.

And yes, building llvm is an utter pain, hunter abstracts that away (it does not necessarily use cmake as the build system for the things you bring in through it, it supports any method of building, and for LLVM it uses the official LLVM build system).  Ditto with [clang](https://docs.hunter.sh/en/latest/packages/pkg/Clang.html) and its tools as well.

**Comment by multigrid101** [comment]
The problem seems to be that the directory structure in the pre-built llvm/clang release is different from that in the self-built release. But not only is the structure different, some `.inc` files that exist in the pre-built version do not seem to exist in the self-built version. I have to time to find out the exact cause and a fix right now, but feel free to assign this issue to me (if possible) and I will look into it at some point.

Thanks for the feedback anyway :)

Another note in case anyone needs to know: I had to link my application (a cpp application that uses some terra-generated C API) against `libz` when using the self-built llvm/clang, this wasn't the case with the pre-built binaries and the error wasn't caught by any existing terra tests. I will try to find out what exactly caused the problem and provide a test for it when I have time.

**Comment by OvermindDL1** [comment]
> The problem seems to be that the directory structure in the pre-built llvm/clang release is different from that in the self-built release.

If using CMake then you can have it test for a system install else fallback to the built-in install, and regardless of the pathing with either CMake will set it up properly for anything needed (such as includes and libraries), especially that as I recall the `.inc` files aren't supposed to be used by downstream projects, yes?

**Comment by multigrid101** [comment]
It's not up to me to decide if cmake can/will be used but in general I think that it might be a good idea in the long run. If the number of terra-users is growing then so will the number of "hacks" required by the build-system in order to please everybody.

In the short run, a hack in the makefile or at least a documentation update should suffice imho.

**Comment by elliottslaughter** [comment]
When building LLVM, you can disable libz. My standard configure line is:

```
configure --prefix=... --enable-optimized --disable-assertions --disable-zlib --disable-terminfo
```

I strongly recommend building with configure for all versions of LLVM <= 3.8, because of the issues noted in #235.

**Comment by multigrid101** [comment]
Thanks for the info. Maybe this would be worth mentioning in the build section of the readme? Linking the issue should also be fine.

**Comment by elliottslaughter** [comment]
I'm splitting the documentation into its own issue here: #326

If there are any other issues please feel free to let us know.

FYI, there is support for newer LLVM versions now, and also new binaries here: #323
