### ISSUE TITLE
Optimization flags when terra executes

### ISSUE THREAD

**Issue by multigrid101** [zdevito/terra#258]
Hello there,

When I write a program with terra, it seems that some sort of compiler optimization is performed on the program. I.e. if my program was c code, it behaves as if I compiled it with `-O3` instead of `-O0`.

I managed to track down some settings in the terra source code regarding this optimization. More specifically, I found the functions `llvmutil_addoptimizationpasses()` and `llvm_optimizemodule()`.

My questions are:

1.  Are these the only places that perform compile-time optimization or are there others that I overlooked.
2. Why are there two functions? What are their specific jobs?
3. How do I need to set the parameters in these functions to get the equivalent of "debug mode" performance.
4. Would it be possible to pass these options to terra via flags instead of having to manually set them in the source code?

regards

**Comment by elliottslaughter** [comment]
I have some hacky commits here that you're free to borrow to disable optimizations:

Part 1: https://github.com/elliottslaughter/terra/commit/18f77c5fdd4deba8468a19eeb0ad5707ef0a73b5
Part 2: https://github.com/elliottslaughter/terra/commit/c283c8133811a49d589e70b2a256f00f290dfff3

I'm not sure how it would be best to expose this, but I'd personally be happy to have a flag, option, or variable to set disable optimizations. Some of the stuff I do generates some very large functions which take a very long time for LLVM to optimize.

**Comment by multigrid101** [comment]
Thanks a lot for those two hacks, at least they are a quick method to turn optimization on/off *completely*.

Adding flags seems difficult, as I think that we need them in 3 places:

1. When executing a terra program from the command line
2. When saving to an object file
3. terra C API?

Did I forget something? I think that simply having `-On` flags for n=0,1,2,3 would suffice for most users.

I will look further into this in the future, at least the relevant code sections are now documented in an issue :)

**Comment by elliottslaughter** [comment]
As of 1f894112b631b24c8abf41a0bfd1054187d5b8f3 there is now a `:setoptimized(false)` method on functions that you can use to disable optimizations. Hopefully that meets your needs too. If not, feel free to re-open.
