### ISSUE TITLE
Compile error in terra.cpp

### ISSUE THREAD

**Issue by Clyybber** [zdevito/terra#261]
It fails compiling with this error:
`    
g++ -Wall -g -fPIC -I build -I build/include/luajit-2.0/ -I release/include/terra  -I /usr/local/include -I /usr/local/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O0 -fno-common -Wcast-qual -DLLVM_VERSION=38 -DTERRA_LLVM_HEADERS_HAVE_NDEBUG -fno-rtti -Woverloaded-virtual -fvisibility-inlines-hidden -std=c++11 src/terra.cpp -c -o build/terra.o
src/terra.cpp: In function ‘int terra_initwithoptions(lua_State*, terra_Options*)’:
src/terra.cpp:247:67: error: ‘luaJIT_BC_strict’ was not declared in this scope
     err =    terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_strict,luaJIT_BC_strict_SIZE, "strict.lua")
                                                                   ^~~~~~~~~~~~~~~~
src/terra.cpp:247:67: note: suggested alternative: ‘luaX_newstring’
     err =    terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_strict,luaJIT_BC_strict_SIZE, "strict.lua")
                                                                   ^~~~~~~~~~~~~~~~
                                                                   luaX_newstring
src/terra.cpp:247:84: error: ‘luaJIT_BC_strict_SIZE’ was not declared in this scope
     err =    terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_strict,luaJIT_BC_strict_SIZE, "strict.lua")
                                                                                    ^~~~~~~~~~~~~~~~~~~~~
src/terra.cpp:248:67: error: ‘luaJIT_BC_asdl’ was not declared in this scope
           || terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_asdl,luaJIT_BC_asdl_SIZE, "asdl.lua")
                                                                   ^~~~~~~~~~~~~~
src/terra.cpp:248:82: error: ‘luaJIT_BC_asdl_SIZE’ was not declared in this scope
           || terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_asdl,luaJIT_BC_asdl_SIZE, "asdl.lua")
                                                                                  ^~~~~~~~~~~~~~~~~~~
src/terra.cpp:250:67: error: ‘luaJIT_BC_terralib’ was not declared in this scope
           || terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_terralib,luaJIT_BC_terralib_SIZE, "terralib.lua");
                                                                   ^~~~~~~~~~~~~~~~~~
src/terra.cpp:250:86: error: ‘luaJIT_BC_terralib_SIZE’ was not declared in this scope
           || terra_loadandrunbytecodes(T->L,(const unsigned char*)luaJIT_BC_terralib,luaJIT_BC_terralib_SIZE, "terralib.lua");
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:181: build/terra.o] Error 1
    `

**Comment by elliottslaughter** [comment]
Can you please tell us your OS version, compiler version, and which branch/commit you're on for Terra? Also, is this a completely from scratch build (fresh clone) or a dirty build (anything other than a fresh clone, even if you did `make clean`)?

**Comment by Clyybber** [comment]
I'm on arch linux. 64bit Master Branch and it's a fresh clone. Using clang+LLVM 3.8.1 binaries from the LLVM website.

**Comment by elliottslaughter** [comment]
Is there a way to make this repro inside a Docker container or something? I don't have any machines running arch at the moment.

**Comment by Clyybber** [comment]
Hmm, I don't know, I never used Docker.

**Comment by elliottslaughter** [comment]
How about this then: from a fresh install of Arch, what commands would you use to reproduce your failure?

**Comment by teto** [comment]
I've just had this problem, it happens when strict.h is incorrectly generated. For instance in my case luajit could not load the lua scripts in its folder so I had to  do a make clean then `
export LUA_PATH=build/LuaJIT-2.0.4/src/jit/?.lua;${LUA_PATH:+;$LUA_PATH}`
and rebuild

**Comment by elliottslaughter** [comment]
Could one of you please try again on master? Please try both the normal Makefile and the new CMake support, in case one of those fixes it.

**Comment by Clyybber** [comment]
Can confirm that this is fixed.

**Comment by Clyybber** [comment]
I haven't tried the CMake support yet, but this issue is fixed. Will try with CMake asap.
