### ISSUE TITLE
 LLVM can't generate the entry of local function in the function:"JITGlobalValue"

### ISSUE THREAD

**Issue by wenjieshen** [zdevito/terra#273]
Hi all,

The version of my LLVM is 3.8.0.
Terra occurred a problem that I can't generate completed same local function for second JIT module.
In the test(class6.t), the Terra should generate two JIT module but Terra just generate :

`declare internal double @"$C.times2"(%C*)`

instead of

```
declare internal double @"$C.times2"(%C*) {
entry:
    %1 = getelementptr %C, %C* %0, i64 0, i32 1
    %2 = load i32, i32*%1, align 4
    %3 = shl i32 %2, 2
    %4 = sitofp i32 %3 to double
    ret double %4
}

```
LLVM will crash when it can't link the function.

Thank you for your attention.

**Comment by elliottslaughter** [comment]
The linked PR has merged, so I am closing this issue. Thanks again for the fix!
