### ISSUE TITLE
include<stdio.h> fail on window

### ISSUE THREAD

**Issue by billbliss3** [zdevito/terra#275]
On window10, it seems that the terra only work with VS2013 installed in the default path: C:\program files...
Since I install vs2013 in D:\... , so it may be wrong, could you change the terra with a dynamic vs2013 path

![terra1](https://user-images.githubusercontent.com/5949428/39004739-d1245ce0-4430-11e8-8bee-30c689f29279.jpg)

**Comment by cl4ws0n** [comment]
I have VS installed in the default place and I'm still getting this error. I can't link dynamic libs that require the standard library either. How do we point terra in the right direction?

**Comment by billbliss3** [comment]
I just copy the include file to the default path

**Comment by cl4ws0n** [comment]
Well, that might work for you. For me, it just moves the error along to things included by stdio....

**Comment by billbliss3** [comment]
The default path is C:program files...  I just copy the VC/include to that path
