### ISSUE TITLE
llvm no such file or directory   window7

### ISSUE THREAD

**Issue by billbliss3** [zdevito/terra#276]
I just run the example with C++ API on Win7 , but it run out with the warning:

**llvm: no such file or directory**
anyone know where is the default path?

**Comment by elliottslaughter** [comment]
Hi,

I'm not sure most of the active developers have a working Windows dev environment. If you'd like to help, maybe you could set up appveyor so that other devs can help test this? Otherwise I'm not sure what I can do for you.

Thanks.

**Comment by elliottslaughter** [comment]
We've got AppVeyor support now, as well as updated Windows binaries in the latest beta release (see  #323). There are some pending issues but I'm not aware that anyone has reported anything like. I'm closing this issue for now, but please feel free to comment or open a new issue if the new source/binaries have issues.
