### ISSUE TITLE
Prebuilt Windows release version can't find standard headers or link some libraries

### ISSUE THREAD

**Issue by cl4ws0n** [zdevito/terra#277]
I have been messing with terra on my main development machine for quite some time, and found it quite easy to get started. However, this machine has accrued a library of development tools for various things over the years. As a result, I have recently had quite some trouble determining the dependency that terra is missing in my "clean install" Windows 10 virtualbox test environment.

When running my code in the repl in this test environment, I get the error: 
```
fatal error: 'stdio.h' file not found
#include <stdio.h>
```

I have tried installing various visual c redistributables, msbuild tools, clang... Nothing seems to satisfy. I've tried adding `includepath`'s containing various files but it just moves the not found error along to another file every time. 

What are, or should be, the basic dependencies for doing this on Windows 10? It's not stated that there are any, on the site or the release page...

It also seems that `linklibrary` has some dependency as well, as some dlls that work on my dev machine fail to load in the test.

Update:

It seems that what is needed for the standard headers, is both the Windows 10 SDK, and the VS C++ 2017 Build Tools. The SDK gives you `stdio.h` and such, but it depends on the `vsruntime.h`, the build tools being the most size-efficient way to get that.

However, it seems that these headers are quite different than the ones I've been using, as there are numerous errors from conflicts with the c libs I'm using. 

Also, I am unable to `saveob`j as an exe, receiving the error:
```
llvm: program not executable
```

Update the second:

I tried using the VS2015 equivalents of the files mentioned above, and now I can successfully build my executable.

**Comment by elliottslaughter** [comment]
@cl4ws0n Did you fix your problem and if so, can you please describe the fix so that future users know what to do?
