### ISSUE TITLE
Terra implicitly downcasts floats to ints in function arguments

### ISSUE THREAD

**Issue by manopapad** [zdevito/terra#279]
The following code snippet prints `2`. It should be giving a type error.

```
C = terralib.includec('stdio.h')
terra foo(x : int32)
  C.printf('%d\n', x)
end
terra main()
  var x : double = 2.1
  foo(x)
end
main()
```

**Comment by elliottslaughter** [comment]
@zdevito Pointed out that this has the same semantics as C:

```
#include "stdio.h"

void foo(int x) {
  printf("%d\n", x);
}

int main(int argc, char **argv) {
  double x = 2.1;
  foo(x);
}
```

My inclination is to leave it as is; by copying C this is one less thing you have to learn when you learn Terra.

**Comment by manopapad** [comment]
OK, I didn't know that C also works like this (apparently you can get warned about this with -Wfloat-conversion, which is not included in -Wall or -Wextra). In that case, it makes sense to leave this behavior in Terra as well.
