### ISSUE TITLE
Using a newer version of LLVM?

### ISSUE THREAD

**Issue by moonheart08** [zdevito/terra#283]
I'm using Arch (yes i know i know) and, of course, it's impossible for me to have the standard LLVM/Clang packages at the same time as the ones needed for Terra.
This is fairly minor, you can just clone the repos and use those, but it's nice to have an easier build process.

**Comment by elliottslaughter** [comment]
This is a constant paper cut for us and is something I'd appreciate help on.

Unfortunately, LLVM doesn't maintain backwards compatibility between major releases so this is an issue for basically anyone developing on top of LLVM (not just us). Right now the project just doesn't have enough bandwidth to keep up with LLVM changes. I don't expect this to become a priority until there is a CUDA release that requires an update. Currently NVVM is still on LLVM 3.8.

I'd be happy to accept patches for updated LLVM support, but aside from that I'm not sure if there is anything I can offer you.

**Comment by OvermindDL1** [comment]
I thought the C API of LLVM kept backwards compat between major versions, that it was only the C++ API that broke?

**Comment by elliottslaughter** [comment]
This is true, but the C API is a small subset of what the C++ API supports, and I don't know very many projects that are able to actually use it. Terra itself uses the C++ API.

If we could start from scratch, a better approach would probably be to copy what [llvmlite](https://github.com/numba/llvmlite) does. They have replicated the AST data types in pure Python, without any use of the LLVM APIs at all. This means they can build an AST in Python, serialize it, and hand it off to be parsed and compiled by the LLVM C API. There are still periodic changes to the IR and C APIs, but the volume is lower than C++ API changes, so in theory this would lead to greater stability. Note though that despite all this, they've found it too much of a burden to support more than one LLVM version per llvmlite version, whereas Terra currently supports 6 LLVM versions, so the llvmlite approach clearly isn't flawless either.

**Comment by bananu7** [comment]
Where can we find which versions are currently supported at any given moment? Is there any information that gets updated?

**Comment by elliottslaughter** [comment]
I added it to the README here: https://github.com/zdevito/terra#supported-llvm-versions

**Comment by elliottslaughter** [comment]
Initial support for LLVM 6.0 was added in #298.
