### ISSUE TITLE
Large terra library size

### ISSUE THREAD

**Issue by slaughterj** [zdevito/terra#289]
I've compiled terra using llvm v3.9 and clang v 3.9 from the LLVM subversion repostitories. The resulting terra.a and terra.so is about 2.6 GB and 1.2 GB respectively. I can get them significantly smaller if I strip them but they are still about 4 times as large as what's available in the binary releases currently available. Is this normal or have I missed something? I've compiled using both void linux and manjaro with the exact same result.

**Comment by elliottslaughter** [comment]
It sounds like you're compiling LLVM from source. I'm guessing you built a `Release` build in CMake? Can you try `MinSizeRel`? As I understand, `Release` enables aggressive inlining at LTO time, which is causing the blow-up. This did not used to be true in the autoconf build, but you don't have that as an option if you're using LLVM 3.9.

We could also consider adding an option to dynamically link LLVM into Terra, but there's not a lot of bandwidth available so you'd probably end up needing to implement this yourself if you wanted it.

**Comment by slaughterj** [comment]
Ah, yes. Adding `MinSizeRel` made a huge difference! Thank you.
