### ISSUE TITLE
Generate object file with -fpic

### ISSUE THREAD

**Issue by chichengumich** [zdevito/terra#292]
I'm currently trying to build a python wrapper for [Opt](https://github.com/niessner/Opt) with ctypes, which needs a shared library to be linked to python. I found Opt uses terralib.saveobj to generate object code and then archived into a static library. Is it possible to use terralib.saveobj to generate position independent code (i.e. -fpic), which can then be compiled into a shared library?

**Comment by elliottslaughter** [comment]
Two things:

1. You can use `terralib.saveobj` to generate a dynamic library directly (i.e. by setting the file extension to `so` or `dylib` or the file kind to `sharedlibrary`).

2. As far as I know, the code path for generating a `.o` is the same one that Terra uses internally when it generates a shared library. So it should already have the equivalent of `-fPIC`.

Is there a specific error you're hitting?

**Comment by chichengumich** [comment]
Thanks! @elliottslaughter You are right, the object files are already position independent. Giving `.so` filename to `terra.saveobj` seems to produce the same result as running `g++ -shared -o libOpt.so wrapper.o`. 
The problem I'm facing is that terra itself is not linked into this shared object. And when trying to load `libOpt.so` in python with `cdll.LoadLibrary('libOpt.so')` result in error `OSError: libOpt.so: undefined symbol: lua_settop`. When I tried to directly load `release/terra.so` in python, the error `OSError: loadLibrary: cannot open shared object file: No such file or directory` occurs. I found a workaround from [Control over symbol exports in GCC](http://anadoxin.org/blog/control-over-symbol-exports-in-gcc.html) by using `g++ -shared -fPIC -o $@ build/wrapper.o -Wl,-export-dynamic -Wl,--whole-archive $(TERRAHOME)lib/libterra.a -Wl,--no-whole-archive -Wl,--version-script=libcode.version`, then specify `echo 'CODEABI_1.0 { global: Opt_*; local: *; };' > libcode.version` to skip symbols in libterra to prevent name collision (which causes segfualt). I found this solution quite ugly. Is there a elegant way to link terra itself inside terra? Thanks!

**Comment by Qix-** [comment]
`undefined symbol: lua_settop` is suspect - afaik Terra doesn't link any runtime into anything, so it shouldn't be looking for anything Lua related unless you have explicitly added Lua into your project.

Alternatively, could you output an object file and then link it manually into a `.so`?

As well, you can also pass linker options to `terralib.saveobj()` as the second parameter - `{'-fPIC'}` should pass it directly to clang when linking.

**Comment by chichengumich** [comment]
@Qix- Thanks! The project I'm working on [Opt](https://github.com/niessner/Opt) is another domain specific language which loads code and compiles it at run time. Thus, including symbol related to lua seems reasonable to me. For your suggestion, indeed manually linking object files into `.so` worked for me.

**Comment by elliottslaughter** [comment]
Just FYI, I think you could also link Terra explicitly with `{'-lterra'}` or similar. By default Terra doesn't do this because it's an explicit goal for Terra to generate code without any additional dependencies. I think Terra would only include a call to Lua if there was a Lua function call embedded in the program you're trying to save.
