### ISSUE TITLE
Construction of llvm_list file fails during build

### ISSUE THREAD

**Issue by lightsighter** [zdevito/terra#295]
This line of the Terra build Makefile doesn't work properly with Ubuntu 16.04, GNU Make 4.1, and GCC 5.4.0:

https://github.com/zdevito/terra/blob/master/Makefile#L207

Instead of writing the results to the expected file, it dumps all the file names to the terminal screen. The build then fails later because the llvm_list file is empty.

**Comment by elliottslaughter** [comment]
Fixed by #300.
