### ISSUE TITLE
Compiling a terra function without invoking it.

### ISSUE THREAD

**Issue by alendit** [zdevito/terra#305]
As far as I understand it, terra functions are JIT-compiled the first time they are invoked. Subsequent invocations seem to run much faster.

Maybe I am overlooking something, but I can't find a way to force the compilation of a terra function without invoking it at the same time.

**Comment by alendit** [comment]
Found it 1 min after creating the issue.

For posterity: you can force compilation with `func:compile()`.

**Comment by elliottslaughter** [comment]
This is correct. I'll also note that you can also save a binary with `terralib.saveobj`, and this will completely remove any JIT from subsequent executions of the binary.
