### ISSUE TITLE
Issue Compiling API C Code

### ISSUE THREAD

**Issue by johannphilippe** [zdevito/terra#319]
Hello ! 
I'm currently trying to compile an audio application i did using Lua and Terra. Since "saveobj" can't (as far as i know) export lua code (only terra code), and since my terra and lua code are really difficult to separate, i decided to compile it with a C code, using Lua/Terra API. 

I'm running with Terra Binaries on Linux Minx Cinnamon 18.3, 64bit. 

Every examples i tried work the same if i use GCC or Clang. 
The C code only contains basic code to import and run my terra/lua code. 
```

#include <stdlib.h>
#include <stdio.h>
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
#include "terra.h"

int main (void) {

FILE *f = fopen("/home/johann/Terra/basiciup.t", "rb");
fseek(f, 0, SEEK_END);
long fsize = ftell(f);
fseek(f, 0, SEEK_SET);  //same as rewind(f);

char *string = malloc(fsize + 1);
fread(string, fsize, 1, f);
fclose(f);
string[fsize] = 0;


 	int error,tstate;
	lua_State *L = luaL_newstate(); 


        tstate=terra_init(L);
        luaL_openlibs(L);	/* opens the standard libraries */
        
        error = terra_loadstring(L,string) || lua_pcall(L,0,0,0);

	if (error) {
		fprintf(stderr, "%s\n", lua_tostring(L, -1));
		lua_pop(L, 1); /* pop error message from the stack */
	}
	lua_close(L);
        return 0;
}
```

I had to add a few linker arguments (here terra requires libdl, libstdc++, libm, and libpthread, the others library are the ones i'm using). 

 `gcc mycode.c -Iinclude/terra -I/usr/include -liuplua51 -liupluacontrols51 -liuplua_plot51 -lcdlua51 -liupluacd51 -liupluaimglib51 -lterra -lm -lpthread -lstdc++ -ldl -L/home/johann/Terra/lib -o myprogram`

And the resulting executable is returning Segmentation Fault. 

To be sure, i tried with a simple lua code (instead of the big one, imported in C) : 
`print("HELLO")`

And compilation with terra library still Segfaults. 
I finally tried to compile this simple lua code with a basic luajit library, and it works fine...

Any idea on what i could be missing here ? 

Thanks

**Comment by johannphilippe** [comment]
Thank you, it works for me too ! 
Didn't know about this.

**Comment by elliottslaughter** [comment]
Glad it worked for you. I'm closing this issue for now, but please feel free to reopen or to open a new issue if you run into further trouble.
