### ISSUE TITLE
Ternary operator

### ISSUE THREAD

**Issue by capr** [zdevito/terra#331]
Hi! 

While converting some Lua code to Terra I have found that I'm using the `and` and `or` operators to simulate the ternary operator `?:` quite often. This doesn't translate to Terra because Terra expects the types of all operands to be the same so I cannot use `bool` as the first operand and say, `int` as the 2nd and 3rd operands. Is there a way to add the ternary operator via a macro or something so that I don't have to use `if then else end` ?

Thanks!

**Comment by elliottslaughter** [comment]
If you don't mind using a macro something like the following ought to work:

```
local ternary = macro(function(c, t, e)
  return quote
    var v : t:gettype()
    if c then
      v = t
    else
      v = e
    end
  in
    v
  end
end)

terra f()
  var x = 123
  return ternary(x > 0, x + 1, x - 1)
end

print(f())
```

Usage:

```
$ terra terra_ternary_expr.t
124
```

**Comment by capr** [comment]
looks like `terralib.select()` is also an option except it's not short-circuiting.

**Comment by elliottslaughter** [comment]
I'm going to close this for now. Please feel free to reopen if there is anything else.
