### ISSUE TITLE
assert() C macro

### ISSUE THREAD

**Issue by capr** [zdevito/terra#332]
Hi!

Is there any way to implement the C `assert()` macro in Terra, IOW are `__FILE__` and `__LINE__` preserved and can they be exposed?

Thanks!

**Comment by elliottslaughter** [comment]
This ought to do the trick:

```
local c = terralib.includecstring([[
#include <stdio.h>
#include <stdlib.h>
]])

local tassert = macro(function(e)
  return quote
    if not e then
      var stderr = c.fdopen(2, "w")
      c.fprintf(stderr, ["assertion failed " .. tostring(e.filename) .. ":" .. tostring(e.linenumber) .. ": " .. tostring(e) .. "\n"])
      c.fflush(stderr) -- stderr isn't always unbuffered
      c.abort()
    end
  end
end)

terra f(x : int)
  tassert(x + 1 == x)
end

f(3)
```

Usage:

```
$ terra terra_assert.t
assertion failed terra_assert.t:18: x + 1 == x
```

Technically filename and linenumber are private APIs, but practically speaking these don't change very frequently (if at all).

**Comment by capr** [comment]
Just what I wanted, thanks! 

Had to do a little adjustment for Windows: 

`local fdopen = ffi.abi'win' and _fdopen or fdopen`

**Comment by elliottslaughter** [comment]
I'm going to close this for now. Please feel free to reopen if there is anything else.
