### ISSUE TITLE
Problem curand_kernel.h cannot be included

### ISSUE THREAD

**Issue by WL63** [zdevito/terra#367]
When I include curand_kernel.h, terra throws out a lot of errors and stops executing
What is it about? I need to get a random number with seed (PRNG) on each thread cuda 
Log with source
[inc.t  inc.log .zip](https://github.com/zdevito/terra/files/3080537/inc.t.inc.log.zip)

**Comment by elliottslaughter** [comment]
Can you try passing `terra.cudatarget` as the 3rd argument to `terralib.includec`/`includecstring`: http://terralang.org/api.html#using-c-inside-terra

**Comment by vlr63** [comment]
`local C = terralib.includecstring("
#include <curand_kernel.h> 
",terralib.cudatarget)`
No, terra keeps throwing the same errors (170 lines). 
I found another solution for my project, but I need to find out what the problem is.

**Comment by vlr63** [comment]
[inc2.zip](https://github.com/zdevito/terra/files/3082171/inc2.zip)
`local C = terralib.includecstring(" #include <curand_kernel.h> ",{"-I"},terralib.cudatarget)`
No, but terra began to produce more errors (~963 lines).
I noticed 2 interesting errors in the log:

> D:\Programming\COMPILERS\Cuda v10.1\dev/include/crt/host_defines.h:143:2: error: --- !!! UNKNOWN COMPILER: please provide a CUDA compatible definition for '__align__' !!! ---

> D:\Programming\COMPILERS\Cuda v10.1\dev/include/crt/host_defines.h:149:2: error: --- !!! UNKNOWN COMPILER: please provide a CUDA compatible definition for 'CUDARTAPI' !!! ---

May need a specific version of Cuda? (Terra passed all tests related to Cuda) Or build your own terralib.cudatarget10_1?

> I found another solution for my project, but i need to find out what the problem is.

**Comment by elliottslaughter** [comment]
I think we need more information to help at this point.

What OS/compiler version are you on? Did you build Terra from source? What LLVM and CUDA versions are you using?

FYI I think the command line would be:

```
local C = terralib.includecstring("#include <curand_kernel.h>", nil, terralib.cudatarget)
```

Because otherwise you're passing an invalid flag into the compiler (`-I` expects a path, so I have no idea what it'll do if you pass it without one).

**Comment by WL63** [comment]
Win10, downloaded "Release 1.0.0-beta1", LLVM 6.0.1, CUDA 10.1
`local C = terralib.includecstring("#include <curand_kernel.h>", nil, terralib.cudatarget)`
The same errors as "with" and "without"

**Comment by elliottslaughter** [comment]
I realize this might be a pain, but it is possible to try CUDA 9.2? I think that's what we built the binaries against. Otherwise you might need to look into building Terra from source.

**Comment by WL63** [comment]
Switching to cuda 9.2 didn’t affect, the same errors
