### ISSUE TITLE
Question: GC in Terra Functions

### ISSUE THREAD

**Issue by turbo** [zdevito/terra#371]
Would it be safe to use C GC implementations inside of terra functions (e.g. Boehm)? I like the typed aspect of terra code but would like to offload memory management to a GC.

**Comment by elliottslaughter** [comment]
As far as I know Terra doesn't do anything that would interfere with this; most optimizations come from LLVM so that part should be fine.

**Comment by elliottslaughter** [comment]
I'm going to close this for now, but if you have more questions please feel free to contact us again.
