### ISSUE TITLE
defer statement only accepts function calls

### ISSUE THREAD

**Issue by aiverson** [zdevito/terra#375]
Why?

I'm not sure I understand why this limitation exists.
Is it just a simplification to make the initial implementation shorter, or is there some technical reason for it?

**Comment by aiverson** [comment]
@elliottslaughter Do you have any insight to share on this?

**Comment by elliottslaughter** [comment]
I'm not aware of any specific reasons, we'd have to ask @zdevito to be sure.

**Comment by zdevito** [comment]
It's to make the semantics clear:
```
terra foo(a: int, b:int): int
  return a + b
end
```

`defer foo(e + f, c + d)`  e + f, e + d are computed eagerly and then just the call to foo is deferred. If other statements were allowed, e.g.  `defer  (e + f) +  (c + d)` it wouldn't be clear that just the inner `+` would be the thing deferred.

**Comment by aiverson** [comment]
Ah. Thanks. That's actually a really nice feature now that I understand why.
