### ISSUE TITLE
tdebug.cpp compilation fails on 32-bit Linux

### ISSUE THREAD

**Issue by afsmi** [zdevito/terra#63]
src/tdebug.cpp does not compile on my 32-bit Linux system.
The problem appears to begin on lines 124 to 126 (in function printstacktrace):

```
#ifdef __linux__
        rip = (void*) uc->uc_mcontext.gregs[REG_RIP];
        rbp = (void*) uc->uc_mcontext.gregs[REG_RBP];
```
As I understand it, REG_RIP and REG_RBP will be undefined here on 32-bit systems.

clang output:
```
/usr/bin/clang++ -g -I build/LuaJIT-2.0.2/src -I /usr/include -I /usr/include -I build -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O0 -fno-rtti -fno-common -Woverloaded-virtual -Wcast-qual -fvisibility-inlines-hidden -DLLVM_3_4 -DTERRA_CLANG_RESOURCE_DIRECTORY="\"/usr/lib/clang/3.4/include\"" src/tdebug.cpp -c -o build/tdebug.o
src/tdebug.cpp:125:45: error: use of undeclared identifier 'REG_RIP'; did you mean 'REG_EIP'?
        rip = (void*) uc->uc_mcontext.gregs[REG_RIP];
                                            ^~~~~~~
                                            REG_EIP
/usr/include/sys/ucontext.h:186:3: note: 'REG_EIP' declared here
  REG_EIP,
  ^
src/tdebug.cpp:126:45: error: use of undeclared identifier 'REG_RBP'; did you mean 'REG_EBP'?
        rbp = (void*) uc->uc_mcontext.gregs[REG_RBP];
                                            ^~~~~~~
                                            REG_EBP
/usr/include/sys/ucontext.h:170:3: note: 'REG_EBP' declared here
  REG_EBP,
  ^
2 errors generated.
Makefile:222: recipe for target 'build/tdebug.o' failed
make: *** [build/tdebug.o] Error 1
```

**Comment by paniq** [comment]
How's the progress on this? I'm on a 32-bit netbook and are running into similar issues

**Comment by zdevito** [comment]
I haven't had time to implement 32-bit calling conventions, so the status is still the same as my earlier comment. It should be possible to compile it and use it by change the tdebug.cpp file to turn off the debug interface, but  some functions that pass or return structs by value, or return multiple values won't work.

**Comment by Asmageddon** [comment]
Ah... I have a 32 bit box and wanted to run Terra. I made tdebug.cpp use EIP and EBP on 32 bit Linux instead, and it runs, but yeah, I realized that I should probably run tests, and there indeed are 31 failing tests. If you don't have time for this, could you provide some pointers, guidelines and advice to contributors potentially interested in this?

**Comment by zdevito** [comment]
I made issues #119 to track support for 32-bit builds.
