### ISSUE TITLE
Access global variables defined by included C libraries

### ISSUE THREAD

**Issue by HalosGhost** [zdevito/terra#71]
Continuing my project of messing around with NCurses under Terra, I've discovered that all the functions and type definitions are easily accessible. E.g.:

    C = {}; C.nc = terralib.includec("ncurses.h")
    var mainwin: &C.nc.WINDOW = C.nc.initscr()

The above works just fine. However, when I test to see what all is available in ``C.nc``, it does not appear that variables themselves are made available (assume I have correctly imported ``stdio.h`` as ``C.io``):

    for k, v in pairs(C.nc) do
        C.io.printf("%s ", k)
    end
    C.io.printf("\n")

The above code yields the following list:

    fseek wclrtoeol waddstr is_nodelay flash has_mouse wgetnstr scrollok getmaxy NCURSES_WINDOW_CB termname putc nodelay inchnstr vidputs fgetc mvaddstr scr_init meta getmouse getbkgd whline addchnstr flockfile subpad int64_t ftrylockfile wtouchln mvgetch NCURSES_BOOL inch waddchnstr puts noqiflush wenclose border noraw mousemask slk_attr_off open_memstream immedok mvwdelch vscanf getpary _IO_padn __u_quad_t uint_least64_t _tracechtype2 mvwhline __io_read_fn mvwinsstr getnstr ssize_t mvderwin mvwaddch putw mvgetstr fscanf getch flushinp color_set attr_off _IO_seekpos sprintf tigetflag __blkcnt_t vwscanw addnstr _tracechar wgetscrreg set_term slk_noutrefresh attr_t move tparm putchar_unlocked __blkcnt64_t __key_t uint64_t vfprintf mvdelch __blksize_t wechochar va_list copywin MEVENT wstandend getc fgets reset_shell_mode mvwgetnstr mvwinsnstr __uint64_t wsetscrreg _traceattr2 __loff_t mouse_trafo delay_output tempnam standout echochar putp inchstr key_defined fsetpos waddchstr halfdelay wsyncdown setbuf isendwin wattr_get getmaxx addchstr _IO_flockfile leaveok insnstr pclose __nlink_t vsprintf __va_list_tag __rlim_t freopen idlok chgat uint_fast8_t screen winch getchar use_default_colors __u_char unctrl wprintw int8_t uint8_t getattrs __uid_t slk_attr_on __u_long slk_attroff fputs wbkgd __off64_t int16_t wchgat int_least64_t pdat overlay fread_unlocked instr _IO_vfprintf winchstr wredrawln vw_scanw getstr remove wattr_set _IO_putc slk_restore getparx fread slk_attron tigetstr slk_refresh vw_printw wattroff wchar_t clrtobot attron touchline _traceattr __overflow raw __int32_t scanw nonl wscanw hline mvwinch __fsfilcnt64_t attroff scrl printw use_legacy_coding scr_restore _tracechtype use_window clear __u_short __intptr_t bkgdset int32_t mvaddchnstr wattrset vfscanf __int16_t fclose __clock_t is_keypad perror define_key is_notimeout trace __caddr_t use_screen int_fast8_t ferror syncok is_immedok chtype addch is_scrollok endwin fflush_unlocked mvwin mvaddnstr popen clearerr nl ferror_unlocked __syscall_ulong_t wbkgdset winchnstr wattr_on is_leaveok delscreen delwin wborder renameat mvinchnstr derwin def_prog_mode mvinstr ctermid erase has_key scr_set ftello putc_unlocked wscrl __id_t mvscanw tmpfile refresh keyok scanf intptr_t _win_st _IO_lock_t getline mvwchgat wattr_off _IO_seekoff _IO_ftrylockfile mvinnstr fwrite_unlocked has_colors ripoffline _IO_getc wstandout qiflush is_cleared keybound set_escdelay slk_label attr_on longname __pid_t int_fast32_t sscanf _IO_feof wresize init_color mvwinchstr _tracemouse getcury deleteln echo mvinsnstr winsertln wtimeout is_linetouched mvinchstr tmpnam mvhline get_escdelay _IO_marker rename __uint32_t assume_default_colors typeahead delch baudrate uint_least16_t nofilter putchar getbegy mmask_t fgetc_unlocked mvwaddchstr fputc getchar_unlocked __rlim64_t keyname __clockid_t pechochar vdprintf __quad_t start_color fdopen fileno_unlocked init_pair mvcur __uint16_t wdelch feof_unlocked wrefresh curs_set termattrs box __io_seek_fn setvbuf FILE int_least32_t wgetdelay NCURSES_SCREEN_CB setbuffer __qaddr_t int_least16_t int_fast16_t fileno uint_least8_t wdeleteln wattron clrtoeol wnoutrefresh PAIR_NUMBER winsnstr wvline doupdate __ino_t has_il def_shell_mode keypad __fsword_t use_tioctl is_term_resized getw slk_init getc_unlocked _IO_jump_t _IO_FILE_plus printf _IO_ferror _tracedump _tracef mcprint wmouse_trafo vsscanf mouseinterval scr_dump has_ic ungetmouse is_syncok __ino64_t insertln _G_fpos64_t is_idlok mvwaddchnstr __syscall_slong_t __uint8_t use_extended_names bkgd _IO_sgetn slk_set ldat addstr NCURSES_OUTC wgetstr int_fast64_t funlockfile feof __mode_t intmax_t winsch vwprintw fseeko uint_least32_t slk_color wcursyncup fputc_unlocked __io_close_fn __int64_t insdelln vprintf clearerr_unlocked snprintf erasechar winstr __fsfilcnt_t __mbstate_t _IO_free_backup_area dprintf __gnuc_va_list attrset __suseconds_t insch _IO_FILE SCREEN mvprintw __uflow slk_attrset _G_fpos_t _IO_funlockfile __timer_t clearok _nc_tracebits notimeout size_t vline __time_t ftell uint_fast64_t mvwscanw mvwinstr mvwinnstr fmemopen gets napms overwrite newwin __useconds_t ptrdiff_t dupwin can_change_color __u_int mvwaddnstr __ssize_t mvgetnstr resizeterm getcurx mvaddchstr is_idcok mvchgat fpos_t killchar filter is_wintouched setscrreg mvinsch redrawwin curses_version ungetc idcok slk_clear mvinch __FILE wgetparent savetty __daddr_t getwin getbegx beep __io_write_fn __getdelim uint32_t is_subwin wclear slk_attr slk_attr_set vidattr tmpnam_r innstr fflush touchwin _IO_peekc_locked __int8_t uint_fast32_t WINDOW set_tabsize initscr __socklen_t tigetnum reset_prog_mode waddch resize_term __off_t mvinsstr attr_set subwin rewind mvvline is_pad COLOR_PAIR attr_get mvwgetstr _IO_vfscanf uint16_t mvwprintw cbreak mvwinsch uint_fast16_t tiparm mvwinchnstr newpad newterm __fsblkcnt64_t noecho fwrite pair_content pnoutrefresh __gid_t resetty scroll fprintf fopen wsyncup uintmax_t fgetpos prefresh mvwvline slk_touch wclrtobot waddnstr getdelim insstr ungetch untouchwin __fsblkcnt_t use_env __dev_t winsstr __fsid_t mvwgetch wcolor_set __> underflow off_t standend int_least8_t werase wgetch mvwaddstr color_content uintptr_t timeout winnstr winsdelln intrflush vsnprintf wmove setlinebuf nocbreak mvaddch putwin

Two variables which are incredibly helpful for doing NCurses layouts (``LINES`` and ``COLS``—the de facto screen size) do not appear in this list even though they are defined in ``ncurses.h`` and initialized by ``initsrc()``.

Is there a way to access such variables?

**Comment by paniq** [comment]
I'm currently in the process of porting my C imports from the ffi interface to the terralib interface, and I've hit a snag with lack of global variable support. GLEW, the GL extension wrangler, makes its GL thunk functions available *after* the GL context has been initialized (on windows, it has to), and they're all defined as global variables. Here's an example:

```
typedef GLboolean (  * PFNGLISSYNCPROC) (GLsync GLsync);
extern  PFNGLISSYNCPROC __glewIsSync;
```

Because this feature is missing, I'm not quite sure how to proceed here.

**Comment by zdevito** [comment]
I don't think I have enough information to know why that crash is occurring. If you want to submit a simple code sample that causes the problem, I might be able to figure out what is going on.

**Comment by HalosGhost** [comment]
looks like this is probably a non-issue as of #100 being merged.
