### ISSUE TITLE
Downloadable binaries

### ISSUE THREAD

**Issue by jimon** [zdevito/terra#78]
I've had a hard time to build terra on win64 (actually I've failed). And I think it's a bit over a line to ask to download LLVM (and build it) and CUDA on a same time. It would be much nicer to provide binaries.

**Comment by zdevito** [comment]
I agree. We are only just now getting the build infrastructure for windows
working. The plan is to eventually distribute it as a binary.

**Comment by den-mentiei** [comment]
Should help a bit with binaries: https://bitbucket.org/Haroogan/llvm-for-windows

**Comment by zdevito** [comment]
Binaries for Windows, Linux, and OSX are now available:
https://github.com/zdevito/terra/releases
