### ISSUE TITLE
Update for LLVM 3.6

### ISSUE THREAD

**Issue by HalosGhost** [zdevito/terra#81]
Now that clang/llvm 3.6 has been released, it would be great if terra progressed to support it.

**Comment by zdevito** [comment]
We will get to it soon -- there are more API changes that we need to sort
through in this version than in previous versions.

**Comment by HalosGhost** [comment]
:+1:

**Comment by mallochine** [comment]
I just realized that I have LLVM 3.6.1, which breaks my build of Terra. What is a recommended version of LLVM to compile Terra with?

**Comment by HalosGhost** [comment]
As far as I know, terra has yet to be updated to LLVM 3.6. 3.5 however, iirc is still compilable.

**Comment by mallochine** [comment]
I'm playing around with terra again. Turns out, only 3.4 is available, not 3.5. Is 3.4 known to be compilable?

**Comment by zdevito** [comment]
3.4 should work fine, though I haven't compiled it with it recently.

**Comment by zdevito** [comment]
LLVM 3.6 support is now working for everything except the CUDA backend and possible some debugging meta-data. For using CUDA, I still recommend 3.5
