### ISSUE TITLE
Custom error contexts?

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#82]
I don't know if this feature is in there already, if it is, I can't find it.

I'm generating terra code from an s-expression based DSL using a handful of generator functions; This works pretty well, but leads to very generic error messages when something goes wrong, such as 

```lua
/home/lritter/devel/duangle/liminal_lua/core/conspire/emit_terra.t:179: definition of this variable is not in scope
    return `func(params)
               ^
```

How can I improve the reporting facilities, and put my own untranslated DSL code here?

**Comment by zdevito** [comment]
This is something we've slowly been working on. For stacktraces, we have
terralib.debuginfo (see tests/customline.t). But this currently doesn't
work for specialization or typechecking errors, which is what is happening
here. In the past, we've written DSL-specific typecheckers to make sure
things translated to Terra will be correct before the compilation actual
happens (e.g. http://darkroom-lang.org). But I am happy to take suggestions
as to how a customizable error reporting facility would work. The difficult
part is knowing who to ask to generate a custom error, and what information
they need to create the error.

**Comment by paniq** [comment]
I'd take cues from the way C compilers do it; A simple #line pragma inserted near the relevant code allows to specify an alternate file and line number for the code that follows.

In analog fashion, I would imagine, at the simplest level

1. I tag objects returned by quote, `, struct, proc, (whatever is appropriate) with context objects of my choosing; ideally any kind of table.
2. Terra can then call tostring(ctx) it whenever it needs to convert one of these context objects back to an error string.

**Comment by paniq** [comment]
An update here: it appears that it is straightforward to take quotes and make changes to ``obj.tree.filename`` and ``obj.tree.linenumber``; ``obj.tree.object`` can either be set to ``nil`` to supress a context dump, or to a character index within the file, if available, which then provides some output directly from the file.

It appears that it doesn't matter here what format the target file has. Therefore I consider the feature implemented.
