### ISSUE TITLE
Unable to quote labeled entries in tuples / unnamed structs

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#83]
It seems there is no apparent way of quoting a list of assignments within a tuple initialization.

```lua
-- works (produces {1, 2, 3})
local exprlist = { 1, 2, 3 }
(quote
in
    { [ exprlist ] }
end):printpretty()

-- works (produces {foo = 303}, but only single entry)
local key = "foo"
local value = 303
(quote
in
    { [ key ] = [ value ] }
end):printpretty()

-- attempt A: fails (produces {<lua value: table: 0x40fcbf98>}, not {foo=303,1,2,3})
exprlist = { [key]= value, 1, 2, 3 }
(quote
in
    { [ exprlist ] }
end):printpretty()

-- attempt B: fails (syntax error: 'end' expected (to close 'quote' at line 25) near '=' )
-- I would have quoted the result as part of a list into { [ exprlist ] }
(quote
in
    [ key ] = [ value ]
end):printpretty()
```

how can I build an unnamed struct procedurally?

**Comment by zdevito** [comment]
We don't have a short syntax to build  named constructors procedurally since they haven't come up that frequently and are semantically different from other things (the statement "a = 4" inside the brackets is itself not an expression, statement, or symbol). You can accomplish it using a composition of other functions if you really needed it:

    local function anonstruct(names) 
        return macro(function(...)
            local exps = terralib.newlist {...}
            local typs = exps:map("gettype")
            local T = terralib.types.newstruct()
            for i,n in ipairs(names) do
                T.entries:insert { n, typs[i] }
            end
            T:setconvertible("named") -- make this type have conversion rules of an anonymous struct typ
            return `T { exps }
        end)
    end

    local struct A {
        b : int
        a : int
    }
    terra foo()    
        var i = [anonstruct({"a","b"})](3,4)
        var a = A(i) -- it converts like an anonymous struct
        return a
    end

    local r = foo()
    print(r.a,r.b)

**Comment by paniq** [comment]
That's a good alternative, thanks.
