### ISSUE TITLE
Failure on RHEL 6.6

### ISSUE THREAD

**Issue by saptarshiguha** [zdevito/terra#88]
Hello,
Tested the terra binary found in https://github.com/zdevito/terra/releases/tag/release-2015-03-12. 
On RHEL 6.6, note that the glic version is 2.12. 

1. Running the main binary fails

      [sguha@a.b.c terra-Linux-x86_64-04fb3e2]$ ./terra
      ./terra: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./terra)
      ./terra: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./terra)
      ./terra: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./terra)
      ./terra: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./terra)
      ./terra: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./terra)

2. Also linking with libterra.so causes a similar error  `GLIBC_2.15' not found (required by lib...)

**Comment by zdevito** [comment]
Our build computer uses Ubuntu 14.04, which uses GLIBC_2.15. I don't have a good way of building binaries for older versions, which is what is necessary to get it to run on that os. Let me know if you have a suggestion. Building from source on the machine should still work.

**Comment by saptarshiguha** [comment]
True. In fact LLVM 3.6 wont even compile on RHEL 6.6 with

"We detected a missing feature in the standard C++ library that was known to be
missing in libstdc++4.6 and implemented in libstdc++4.7. There are numerous
C++11 problems with 4.6's library, and we don't support GCCs or libstdc++ older
than 4.7. You will need to update your system and ensure Clang uses the newer
standard library."
