### ISSUE TITLE
Error while compiling against Clang 3.4 on RHEL 6.6

### ISSUE THREAD

**Issue by saptarshiguha** [zdevito/terra#89]
Hello,
Just compiled Clang 3.4 on RHEL 6.6. Successfully compiled, i checked out Terra and set built it against clang 3.4. Got this error

/opt/clang34/bin/clang++ -Wall -g -fPIC -I build -I release/include -I build/LuaJIT-2.0.3/src -I /opt/clang34/include -I /opt/clang34/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O0 -fno-rtti -fno-common -Woverloaded-virtual -Wcast-qual -fvisibility-inlines-hidden -DLLVM_VERSION=34 -std=c++11 -Wno-c++11-narrowing src/tcompiler.cpp -c -o build/tcompiler.o
In file included from src/tcompiler.cpp:26:
In file included from src/llvmheaders.h:5:
In file included from /opt/clang34/include/clang/AST/RecursiveASTVisitor.h:17:
In file included from /opt/clang34/include/clang/AST/Decl.h:17:
In file included from /opt/clang34/include/clang/AST/APValue.h:18:
In file included from /opt/clang34/include/llvm/ADT/APFloat.h:20:
In file included from /opt/clang34/include/llvm/ADT/APInt.h:19:
In file included from /opt/clang34/include/llvm/ADT/ArrayRef.h:14:
In file included from /opt/clang34/include/llvm/ADT/SmallVector.h:27:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146:24: error: cannot use typeid with -fno-rtti
      { return __ti == typeid(_Deleter) ? &_M_del._M_del : 0; }
                       ^
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204:24: error: cannot use typeid with -fno-rtti
        return __ti == typeid(_Sp_make_shared_tag)
                       ^
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861:50: error: cannot use typeid with -fno-rtti
          void* __p = _M_refcount._M_get_deleter(typeid(__tag));
                                                 ^
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005:52: error: cannot use typeid with -fno-rtti
    { return static_cast<_Del*>(__p._M_get_deleter(typeid(_Del))); }
                                                   ^

**Comment by zdevito** [comment]
Can you try removing "-fno-rtti" from the Terra Makefile and building again?

On my machine LLVM requires that flag to build, but it looks like you might
need the
opposite.

**Comment by saptarshiguha** [comment]
Nopes, i get the following error.

/opt/clang34/bin/clang++ -Wall -g -fPIC -I build -I release/include -I
build/LuaJIT-2.0.3/src -I /opt/clang34/include -I /opt/clang34/include
-D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS
-D__STDC_LIMIT_MACROS -O0  -fno-common -Woverloaded-virtual -Wcast-qual
-fvisibility-inlines-hidden -DLLVM_VERSION=34 -std=c++11
-Wno-c++11-narrowing src/tcompiler.cpp -c -o build/tcompiler.o
In file included from src/tcompiler.cpp:26:
In file included from src/llvmheaders.h:5:
In file included from
/opt/clang34/include/clang/AST/RecursiveASTVisitor.h:18:
In file included from /opt/clang34/include/clang/AST/DeclCXX.h:21:
In file included from /opt/clang34/include/clang/AST/Expr.h:22:
In file included from /opt/clang34/include/clang/AST/Stmt.h:18:
/opt/clang34/include/clang/AST/StmtIterator.h:164:15: error: call to
implicitly-deleted copy constructor of 'clang::StmtRange'
    StmtRange copy = *this;
              ^      ~~~~~
/opt/clang34/include/clang/AST/StmtIterator.h:145:20: note: copy
constructor of 'StmtRange' is implicitly deleted because base class
'std::pair<StmtIterator, StmtIterator>' has a deleted copy constructor
struct StmtRange : std::pair<StmtIterator,StmtIterator> {
                   ^
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:92:7:
note: copy constructor is implicitly deleted because
'pair<clang::StmtIterator, clang::StmtIterator>' has a
      user-declared move constructor
      pair(pair&& __p)
      ^
In file included from src/tcompiler.cpp:26:
In file included from src/llvmheaders.h:5:
In file included from
/opt/clang34/include/clang/AST/RecursiveASTVisitor.h:18:
In file included from /opt/clang34/include/clang/AST/DeclCXX.h:21:
In file included from /opt/clang34/include/clang/AST/Expr.h:22:
In file included from /opt/clang34/include/clang/AST/Stmt.h:18:

**Comment by zdevito** [comment]
Ok, try removing the -std=c++11 now.

**Comment by saptarshiguha** [comment]
Almost there (thanks for your time on this). Now this error (at the linking
stage for the executable, the library has a similar error when loading)

(command : https://sguha.pastebin.mozilla.org/8830539 )

E]+0x10): undefined reference to `typeinfo for llvm::CallbackVH'
build/libterra.a(tcompiler.o):(.data.rel.ro._ZTI27DisassembleFunctionListener[_ZTI27DisassembleFunctionListener]+0x10):
undefined reference to `typeinfo for llvm::JITEventListener'
build/libterra.a(tllvmutil.o):(.data.rel.ro._ZTI22CopyConnectedComponent[_ZTI22CopyConnectedComponent]+0x10):
undefined reference to `typeinfo for llvm::ValueMaterializer'
build/libterra.a(tllvmutil.o):(.data.rel.ro._ZTI18SimpleMemoryObject[_ZTI18SimpleMemoryObject]+0x10):
undefined reference to `typeinfo for llvm::MemoryObject'
build/libterra.a(tllvmutil.o):(.data.rel.ro._ZTI18PassManagerWrapper[_ZTI18PassManagerWrapper]+0x10):
undefined reference to `typeinfo for llvm::legacy::PassManagerBase'
build/libterra.a(tcwrapper.o):(.data.rel.ro._ZTI12CodeGenProxy[_ZTI12CodeGenProxy]+0x10):
undefined reference to `typeinfo for clang::ASTConsumer'

**Comment by zdevito** [comment]
This appears to be a bug in gcc:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=42019

LLVM is compiled with -fno-rtti, but it uses shared_ptr in one of its
headers, with GCC 4.4 requires RTTI enabled.

If you really need to run on this platform, you can recompile LLVM with
this environment variable set:

REQUIRES_RTTI=1

And then compile Terra without the -fno-rtti flag.

**Comment by saptarshiguha** [comment]
Thanks much. If anyone else does this, compile Terra without -fno-rtti  flag and without  -std=c++11 flag.
This is for Clang 3.4 on RHEL 6.6 and glibc 2.12.
Thanks again.
