### ISSUE TITLE
Custom operators for usage of cdata in Lua?

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#90]
The manual provides a mechanism for operators as metamethods that are used by terra code, but those metamethods do not seem to work in a Lua context:

```lua

local struct S {
    x : int
    y : int
}

-- declaring new + operator
S.metamethods.__add = terra (self : &S, other : &S) : S
    var result : S
    result.x = self.x + other.x
    result.y = self.y + other.y
    return result
end

-- this works fine
local terra testfunc()
    var a = S { 1, 2 }
    var b = S { 3, 4 }
    
    var c = a + b
    
    print(c.x, c.y)

end
testfunc()

-- this fails
-- attempt to perform arithmetic on 'struct S' and 'struct S'
local a = terralib.new(S,1,2)
local b = terralib.new(S,3,4)
local c = a + b
print(c.x, c.y)

-- but this works
c = S.metamethods.__add(a,b)
print(c.x, c.y)
```

is there a way to augment S so that using it conveniently in a Lua context is possible? ffi.metatype does not seem to apply here.

**Comment by zdevito** [comment]
We have this implemented for calling methods on terra objects from Lua, but we haven't implemented the logic for other operators like + yet. I'll leave this issue open to track this feature.

**Comment by paniq** [comment]
I found after studying the source code that this feature is already attainable. ``metamethods.__luametatable`` can be set to the metatype assigned to cdata, and ``__add`` and other operators can be defined there. Therefore I consider the feature implemented.
