### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by fuzzthink** [zdevito/terra#93]
What's the difference between `local` and `var`?

Is `somestruct.alloc()` GC'ed? Some examples calls `free()` on the instances while most don't.

Can `alloc` be called on non-structs? How is it related to `terralib.new`?

How does 0-based indexes work with Lua's 1-based indexes codebase?

thanks.

**Comment by fuzzthink** [comment]
I see there's a mailing list, will post there since more appropriate. closing.

**Comment by dumblob** [comment]
@fuzzthink could you please post the answers you got on mailing list here?

**Comment by fuzzthink** [comment]
Asked in list, no one ever replied.

**Comment by dumblob** [comment]
@zdevito how is indexing handled when interleaving Lua and Terra code? Any caveats? How is it with the other questions @fuzzthink asked above?

Thank you in advance. Terra seems to be great for many purposes (now I'm looking into how to port existing Lua code bases to Terra to achieve significantly higher performance).
