### ISSUE TITLE
Add support for Windows MinGW

### ISSUE THREAD

**Issue by arkdemon** [zdevito/terra#94]
Hello,
is it possible to make Terra Lua support MinGW (4.9) on Windows?
Thank you!

**Comment by elliottslaughter** [comment]
@arkdemon Do you still care about this?

**Comment by elliottslaughter** [comment]
Closing since there hasn't been activity on this issue, but for the record, the new CMake build should make this much easier to implement. The main issue is finding someone with the time and interest to do it.
