### ISSUE TITLE
terra as a library

### ISSUE THREAD

**Issue by capr** [zdevito/terra#95]
Hi,

Could we have a libterra build that doesn't include luajit but instead links to it dynamically? 

This would allow me to:
- write a Lua/C wrapper for terra.h that will allow it to be included in a normal luajit installation with `require'terra' which would bind terra to the main Lua state of the program.
- the wrapper will also add a require() loader that would allow loading *.t files with require().

This will enable luajit apps that contain a mix of lua and terra modules. I did this for dynasm[1](you can load .dasl files with standard require).

I could do this myself of course, but I wanted to ask first in case you already thought about this, or maybe you think this wouldn't work or is not a good idea, in which case I would like to know before I start :)

Kudos for terra btw, it's a really really cool project.

[1] https://luapower.com/dynasm

**Comment by zdevito** [comment]
I think this would work, so go ahead and try if you want. This should be
possible with some small modifications. To remove the linking against
LuaJIT, just remove:

Line 73 (osx): ,--whole-archive $(LUAJIT_LIB)
Line 70 (linux): $(LUAJIT_LIB)

You will also need to edit src/treadnumber.c to directly include
lj_strscan.c and lj_char.c (This is already done for windows).

Terra already adds a require() load for .t files when it is initialized, so
you won't have to that.

Let me know if you run into issues.





On Sun, May 24, 2015 at 2:29 AM, Cosmin Apreutesei <notifications@github.com

**Comment by capr** [comment]
That was easy indeed[1]. Building LLVM was hell though :( Now the only obstacle to total world domination is porting terra to 32bit... though I see you're busy with cuda these days :) Btw, is your cuda code related to terracuda or is that a totally un unrelated project?

[1] https://luapower.com/terra

**Comment by alexbw** [comment]
Bump on this thread, is terra from this repo importable as a library into LuaJIT? Or is this a separate branch that you're maintaining @capr?

**Comment by capr** [comment]
@alexbw terra from luapower has a few trivial modifications which makes it build separately from luajit (the changes are documented at the link above; the build scripts are also hand-made)

**Comment by alexbw** [comment]
Thanks for the heads up. You plan on pushing changes upstream, or are they
specific enough to your set of modules to keep it separate? Also, do your
changes enable building with vanilla Lua?

On Sun, Nov 15, 2015 at 1:11 PM, Cosmin Apreutesei <notifications@github.com

**Comment by capr** [comment]
@alexbw I have different build scripts so wouldn't make sense to push them and wouldn't be accepted. You can either ask @zdevito for a solution in upstream, or update my fork with the upstream and rebuild it with luapower scripts and toolchain. As for vanilla Lua, Terra makes extensive use of LuaJIT ffi so they're married together for life :) Btw, this is getting a bit off-topic, we can make more noise at the luapower forum if you like.

**Comment by elliottslaughter** [comment]
This is now supported by the CMake build with `-DTERRA_STATIC_LINK_LUAJIT=OFF` and `-DTERRA_STATIC_LINK_LLVM=OFF`. Please test this with master and file new issues if there are problems with this support.
