### ISSUE TITLE
float (0xB3, 0x79, 0xBE, 0xFF) segfaults if used

### ISSUE THREAD

**Issue by PyryM** [zdevito/terra#97]
Here's an example (which will crash even the online emscriptened interpreter):
```
struct FourBytes {
	b: uint8[4];
}

-- NaN
badbytes = terralib.new(FourBytes)
badbytes.b[0] = 0xB3 -- 179
badbytes.b[1] = 0x79 -- 121
badbytes.b[2] = 0xBE -- 190
badbytes.b[3] = 0xFF -- 255

-- 1.0
goodbytes = terralib.new(FourBytes)
goodbytes.b[0] = 0x00
goodbytes.b[1] = 0x00
goodbytes.b[2] = 0x80
goodbytes.b[3] = 0x3F

terra crashme(input: &uint8)
	var retptr: &float = [&float](input)
	return @retptr
end

terra returnNaN()
	var ret: float = 0.0f / 0.0f
	return ret
end

print("This will work: " .. crashme(goodbytes.b))
print("This will also work: " .. returnNaN())
print("This will segfault: " .. crashme(badbytes.b))
```
The value doesn't immediately segfault terra if it is simply stored, but performing any kind of operation on it will cause the program to segfault in lj_tab_getstr (so this is probably a luajit problem rather than a terra one specifically, although nobody seems to have ever encountered it before).

**Comment by PyryM** [comment]
I think what is happening is that the "NaN tagging" that LuaJIT uses internally to type values is interpreting this non-standard NaN as either a pointer or a string, and then following it which causes the segfault.

**Comment by zdevito** [comment]
Yes, this is actually expected LuaJIT semantics for its ffi interface (which is what we use for Terra). It would not be easy to fix without a large overhead incurred.

**Comment by PyryM** [comment]
Yes, having luajit/terra validate all returned floats would probably be overkill. Still, it's a bit worrisome that any c/terra function that returns a float or double can potentially create a malformed 'number' that can have all kinds of unpredictable behavior when it is used (which might be long after the value is actually returned).

I'm going to go ahead and close this since it doesn't seem like there's any feasible solution in the short term. It would be nice if there were a note in the documentation, though-- I only figured out what was happening by seeing vague hints about "NaN tagging" and ultimately inspecting the luajit source.
